package cn.log.mappers;

import cn.log.pojo.LgCargodetails;
import java.util.List;

public interface LgCargodetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_cargodetails
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer cargodetailsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_cargodetails
     *
     * @mbggenerated
     */
    int insert(LgCargodetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_cargodetails
     *
     * @mbggenerated
     */
    LgCargodetails selectByPrimaryKey(Integer cargodetailsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_cargodetails
     *
     * @mbggenerated
     */
    List<LgCargodetails> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_cargodetails
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgCargodetails record);
}