package cn.log.mappers;

import cn.log.pojo.LgEtrustmentslip;
import java.util.List;

public interface LgEtrustmentslipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_etrustmentslip
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer entrustmentslipid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_etrustmentslip
     *
     * @mbggenerated
     */
    int insert(LgEtrustmentslip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_etrustmentslip
     *
     * @mbggenerated
     */
    LgEtrustmentslip selectByPrimaryKey(Integer entrustmentslipid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_etrustmentslip
     *
     * @mbggenerated
     */
    List<LgEtrustmentslip> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_etrustmentslip
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgEtrustmentslip record);
}