package cn.log.mappers;

import cn.log.pojo.LgFreightcharges;
import java.util.List;

public interface LgFreightchargesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_freightcharges
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer freightchargesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_freightcharges
     *
     * @mbggenerated
     */
    int insert(LgFreightcharges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_freightcharges
     *
     * @mbggenerated
     */
    LgFreightcharges selectByPrimaryKey(Integer freightchargesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_freightcharges
     *
     * @mbggenerated
     */
    List<LgFreightcharges> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_freightcharges
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgFreightcharges record);
}