package cn.log.mappers;

import cn.log.pojo.LgGoodstypecharges;
import java.util.List;

public interface LgGoodstypechargesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_goodstypecharges
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer goodstypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_goodstypecharges
     *
     * @mbggenerated
     */
    int insert(LgGoodstypecharges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_goodstypecharges
     *
     * @mbggenerated
     */
    LgGoodstypecharges selectByPrimaryKey(Integer goodstypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_goodstypecharges
     *
     * @mbggenerated
     */
    List<LgGoodstypecharges> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_goodstypecharges
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgGoodstypecharges record);
}