package cn.log.mappers;

import cn.log.pojo.LgGoodstype;
import java.util.List;

public interface LgGoodstypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_goodstype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer goodstypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_goodstype
     *
     * @mbggenerated
     */
    int insert(LgGoodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_goodstype
     *
     * @mbggenerated
     */
    LgGoodstype selectByPrimaryKey(Integer goodstypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_goodstype
     *
     * @mbggenerated
     */
    List<LgGoodstype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_goodstype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgGoodstype record);
}