package cn.log.mappers;

import cn.log.pojo.LgIncome;
import java.util.List;

public interface LgIncomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_income
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer incomeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_income
     *
     * @mbggenerated
     */
    int insert(LgIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_income
     *
     * @mbggenerated
     */
    LgIncome selectByPrimaryKey(Integer incomeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_income
     *
     * @mbggenerated
     */
    List<LgIncome> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_income
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgIncome record);
}