package cn.log.mappers;

import cn.log.pojo.LgOrderwaybill;
import java.util.List;

public interface LgOrderwaybillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_orderwaybill
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer orderwaybillid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_orderwaybill
     *
     * @mbggenerated
     */
    int insert(LgOrderwaybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_orderwaybill
     *
     * @mbggenerated
     */
    LgOrderwaybill selectByPrimaryKey(Integer orderwaybillid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_orderwaybill
     *
     * @mbggenerated
     */
    List<LgOrderwaybill> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_orderwaybill
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgOrderwaybill record);
}