package cn.log.mappers;

import cn.log.pojo.LgOrdergoods;
import java.util.List;

public interface LgOrdergoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_ordergoods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ordergoodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_ordergoods
     *
     * @mbggenerated
     */
    int insert(LgOrdergoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_ordergoods
     *
     * @mbggenerated
     */
    LgOrdergoods selectByPrimaryKey(Integer ordergoodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_ordergoods
     *
     * @mbggenerated
     */
    List<LgOrdergoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_ordergoods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgOrdergoods record);
}