package cn.log.mappers;

import cn.log.pojo.LgOutbound;
import java.util.List;

public interface LgOutboundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_outbound
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer outboundid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_outbound
     *
     * @mbggenerated
     */
    int insert(LgOutbound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_outbound
     *
     * @mbggenerated
     */
    LgOutbound selectByPrimaryKey(Integer outboundid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_outbound
     *
     * @mbggenerated
     */
    List<LgOutbound> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_outbound
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgOutbound record);
}