package cn.log.mappers;

import cn.log.pojo.LgOutboundgoods;
import java.util.List;

public interface LgOutboundgoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_outboundgoods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer outboundgoodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_outboundgoods
     *
     * @mbggenerated
     */
    int insert(LgOutboundgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_outboundgoods
     *
     * @mbggenerated
     */
    LgOutboundgoods selectByPrimaryKey(Integer outboundgoodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_outboundgoods
     *
     * @mbggenerated
     */
    List<LgOutboundgoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_outboundgoods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgOutboundgoods record);
}