package cn.log.mappers;

import cn.log.pojo.LgPerms;
import java.util.List;

public interface LgPermsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_perms
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer permsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_perms
     *
     * @mbggenerated
     */
    int insert(LgPerms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_perms
     *
     * @mbggenerated
     */
    LgPerms selectByPrimaryKey(Integer permsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_perms
     *
     * @mbggenerated
     */
    List<LgPerms> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_perms
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgPerms record);
}