package cn.log.mappers;

import cn.log.pojo.LgReceipt;
import java.util.List;

public interface LgReceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_receipt
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer receiptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_receipt
     *
     * @mbggenerated
     */
    int insert(LgReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_receipt
     *
     * @mbggenerated
     */
    LgReceipt selectByPrimaryKey(Integer receiptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_receipt
     *
     * @mbggenerated
     */
    List<LgReceipt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_receipt
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgReceipt record);
}