package cn.log.mappers;

import cn.log.pojo.LgReceivingparty;
import java.util.List;

public interface LgReceivingpartyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_receivingparty
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer receivingpartyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_receivingparty
     *
     * @mbggenerated
     */
    int insert(LgReceivingparty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_receivingparty
     *
     * @mbggenerated
     */
    LgReceivingparty selectByPrimaryKey(Integer receivingpartyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_receivingparty
     *
     * @mbggenerated
     */
    List<LgReceivingparty> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_receivingparty
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgReceivingparty record);
}