package cn.log.mappers;

import cn.log.pojo.LgRolePerm;
import java.util.List;

public interface LgRolePermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_role_perm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_role_perm
     *
     * @mbggenerated
     */
    int insert(LgRolePerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_role_perm
     *
     * @mbggenerated
     */
    LgRolePerm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_role_perm
     *
     * @mbggenerated
     */
    List<LgRolePerm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_role_perm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgRolePerm record);
}