package cn.log.mappers;

import cn.log.pojo.LgRole;
import java.util.List;

public interface LgRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_role
     *
     * @mbggenerated
     */
    int insert(LgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_role
     *
     * @mbggenerated
     */
    LgRole selectByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_role
     *
     * @mbggenerated
     */
    List<LgRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgRole record);
}