package cn.log.mappers;

import cn.log.pojo.LgTransferstation;
import java.util.List;

public interface LgTransferstationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_transferstation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer transferstationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_transferstation
     *
     * @mbggenerated
     */
    int insert(LgTransferstation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_transferstation
     *
     * @mbggenerated
     */
    LgTransferstation selectByPrimaryKey(Integer transferstationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_transferstation
     *
     * @mbggenerated
     */
    List<LgTransferstation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_transferstation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgTransferstation record);
}