package cn.log.mappers;

import cn.log.pojo.LgUserRole;
import java.util.List;

public interface LgUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_user_role
     *
     * @mbggenerated
     */
    int insert(LgUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_user_role
     *
     * @mbggenerated
     */
    LgUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_user_role
     *
     * @mbggenerated
     */
    List<LgUserRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgUserRole record);
}