package cn.log.mappers;

import cn.log.pojo.LgUser;
import java.util.List;

public interface LgUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_user
     *
     * @mbggenerated
     */
    int insert(LgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_user
     *
     * @mbggenerated
     */
    LgUser selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_user
     *
     * @mbggenerated
     */
    List<LgUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgUser record);
}