package cn.log.mappers;

import cn.log.pojo.LgVehicleoperation;
import java.util.List;

public interface LgVehicleoperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleoperation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer vehicleoperationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleoperation
     *
     * @mbggenerated
     */
    int insert(LgVehicleoperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleoperation
     *
     * @mbggenerated
     */
    LgVehicleoperation selectByPrimaryKey(Integer vehicleoperationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleoperation
     *
     * @mbggenerated
     */
    List<LgVehicleoperation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleoperation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgVehicleoperation record);
}