package cn.log.mappers;

import cn.log.pojo.LgVehicleline;
import java.util.List;

public interface LgVehiclelineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleline
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer vehiclelineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleline
     *
     * @mbggenerated
     */
    int insert(LgVehicleline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleline
     *
     * @mbggenerated
     */
    LgVehicleline selectByPrimaryKey(Integer vehiclelineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleline
     *
     * @mbggenerated
     */
    List<LgVehicleline> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleline
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgVehicleline record);
}