package cn.log.mappers;

import cn.log.pojo.LgVehiclelineway;
import java.util.List;

public interface LgVehiclelinewayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehiclelineway
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer vehiclelinewayid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehiclelineway
     *
     * @mbggenerated
     */
    int insert(LgVehiclelineway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehiclelineway
     *
     * @mbggenerated
     */
    LgVehiclelineway selectByPrimaryKey(Integer vehiclelinewayid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehiclelineway
     *
     * @mbggenerated
     */
    List<LgVehiclelineway> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehiclelineway
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgVehiclelineway record);
}