package cn.log.mappers;

import cn.log.pojo.LgVehiclemaintenance;
import java.util.List;

public interface LgVehiclemaintenanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehiclemaintenance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer vehiclemaintenanceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehiclemaintenance
     *
     * @mbggenerated
     */
    int insert(LgVehiclemaintenance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehiclemaintenance
     *
     * @mbggenerated
     */
    LgVehiclemaintenance selectByPrimaryKey(Integer vehiclemaintenanceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehiclemaintenance
     *
     * @mbggenerated
     */
    List<LgVehiclemaintenance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehiclemaintenance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgVehiclemaintenance record);
}