package cn.log.mappers;

import cn.log.pojo.LgVehicleinspection;
import java.util.List;

public interface LgVehicleinspectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleinspection
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer vehicleoperationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleinspection
     *
     * @mbggenerated
     */
    int insert(LgVehicleinspection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleinspection
     *
     * @mbggenerated
     */
    LgVehicleinspection selectByPrimaryKey(Integer vehicleoperationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleinspection
     *
     * @mbggenerated
     */
    List<LgVehicleinspection> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleinspection
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgVehicleinspection record);
}