package cn.log.mappers;

import cn.log.pojo.LgWaybill;
import java.util.List;

public interface LgWaybillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_waybill
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer waybillid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_waybill
     *
     * @mbggenerated
     */
    int insert(LgWaybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_waybill
     *
     * @mbggenerated
     */
    LgWaybill selectByPrimaryKey(Integer waybillid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_waybill
     *
     * @mbggenerated
     */
    List<LgWaybill> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_waybill
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgWaybill record);
}