package cn.log.mappers;

import cn.log.pojo.LgWarehousing;
import java.util.List;

public interface LgWarehousingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_warehousing
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer warehousingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_warehousing
     *
     * @mbggenerated
     */
    int insert(LgWarehousing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_warehousing
     *
     * @mbggenerated
     */
    LgWarehousing selectByPrimaryKey(Integer warehousingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_warehousing
     *
     * @mbggenerated
     */
    List<LgWarehousing> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_warehousing
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgWarehousing record);
}