package cn.log.mappers;

import cn.log.pojo.LgWaybillgoods;
import java.util.List;

public interface LgWaybillgoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_waybillgoods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer waybillgoodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_waybillgoods
     *
     * @mbggenerated
     */
    int insert(LgWaybillgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_waybillgoods
     *
     * @mbggenerated
     */
    LgWaybillgoods selectByPrimaryKey(Integer waybillgoodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_waybillgoods
     *
     * @mbggenerated
     */
    List<LgWaybillgoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_waybillgoods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgWaybillgoods record);
}