package cn.log.mappers;

import cn.log.pojo.LgWarehousinggoods;
import java.util.List;

public interface LgWarehousinggoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_warehousinggoods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer warehousinggoodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_warehousinggoods
     *
     * @mbggenerated
     */
    int insert(LgWarehousinggoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_warehousinggoods
     *
     * @mbggenerated
     */
    LgWarehousinggoods selectByPrimaryKey(Integer warehousinggoodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_warehousinggoods
     *
     * @mbggenerated
     */
    List<LgWarehousinggoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_warehousinggoods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LgWarehousinggoods record);
}