package cn.log.pojo;

import java.io.Serializable;

public class LgCargodetails implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_cargodetails.cargoDetailsId
     *
     * @mbggenerated
     */
    private Integer cargodetailsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_cargodetails.predictedQuantity
     *
     * @mbggenerated
     */
    private Integer predictedquantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_cargodetails.predictedVolume
     *
     * @mbggenerated
     */
    private Double predictedvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_cargodetails.predictedWeight
     *
     * @mbggenerated
     */
    private Double predictedweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_cargodetails.originGoodsId
     *
     * @mbggenerated
     */
    private Integer origingoodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_cargodetails.arrivalGoodsId
     *
     * @mbggenerated
     */
    private Integer arrivalgoodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_cargodetails.deliveryMode
     *
     * @mbggenerated
     */
    private Integer deliverymode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_cargodetails.accountingCost
     *
     * @mbggenerated
     */
    private Double accountingcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_cargodetails.receiptPerson
     *
     * @mbggenerated
     */
    private String receiptperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_cargodetails.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_cargodetails.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_cargodetails
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_cargodetails.cargoDetailsId
     *
     * @return the value of lg_cargodetails.cargoDetailsId
     *
     * @mbggenerated
     */
    public Integer getCargodetailsid() {
        return cargodetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_cargodetails.cargoDetailsId
     *
     * @param cargodetailsid the value for lg_cargodetails.cargoDetailsId
     *
     * @mbggenerated
     */
    public void setCargodetailsid(Integer cargodetailsid) {
        this.cargodetailsid = cargodetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_cargodetails.predictedQuantity
     *
     * @return the value of lg_cargodetails.predictedQuantity
     *
     * @mbggenerated
     */
    public Integer getPredictedquantity() {
        return predictedquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_cargodetails.predictedQuantity
     *
     * @param predictedquantity the value for lg_cargodetails.predictedQuantity
     *
     * @mbggenerated
     */
    public void setPredictedquantity(Integer predictedquantity) {
        this.predictedquantity = predictedquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_cargodetails.predictedVolume
     *
     * @return the value of lg_cargodetails.predictedVolume
     *
     * @mbggenerated
     */
    public Double getPredictedvolume() {
        return predictedvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_cargodetails.predictedVolume
     *
     * @param predictedvolume the value for lg_cargodetails.predictedVolume
     *
     * @mbggenerated
     */
    public void setPredictedvolume(Double predictedvolume) {
        this.predictedvolume = predictedvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_cargodetails.predictedWeight
     *
     * @return the value of lg_cargodetails.predictedWeight
     *
     * @mbggenerated
     */
    public Double getPredictedweight() {
        return predictedweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_cargodetails.predictedWeight
     *
     * @param predictedweight the value for lg_cargodetails.predictedWeight
     *
     * @mbggenerated
     */
    public void setPredictedweight(Double predictedweight) {
        this.predictedweight = predictedweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_cargodetails.originGoodsId
     *
     * @return the value of lg_cargodetails.originGoodsId
     *
     * @mbggenerated
     */
    public Integer getOrigingoodsid() {
        return origingoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_cargodetails.originGoodsId
     *
     * @param origingoodsid the value for lg_cargodetails.originGoodsId
     *
     * @mbggenerated
     */
    public void setOrigingoodsid(Integer origingoodsid) {
        this.origingoodsid = origingoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_cargodetails.arrivalGoodsId
     *
     * @return the value of lg_cargodetails.arrivalGoodsId
     *
     * @mbggenerated
     */
    public Integer getArrivalgoodsid() {
        return arrivalgoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_cargodetails.arrivalGoodsId
     *
     * @param arrivalgoodsid the value for lg_cargodetails.arrivalGoodsId
     *
     * @mbggenerated
     */
    public void setArrivalgoodsid(Integer arrivalgoodsid) {
        this.arrivalgoodsid = arrivalgoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_cargodetails.deliveryMode
     *
     * @return the value of lg_cargodetails.deliveryMode
     *
     * @mbggenerated
     */
    public Integer getDeliverymode() {
        return deliverymode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_cargodetails.deliveryMode
     *
     * @param deliverymode the value for lg_cargodetails.deliveryMode
     *
     * @mbggenerated
     */
    public void setDeliverymode(Integer deliverymode) {
        this.deliverymode = deliverymode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_cargodetails.accountingCost
     *
     * @return the value of lg_cargodetails.accountingCost
     *
     * @mbggenerated
     */
    public Double getAccountingcost() {
        return accountingcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_cargodetails.accountingCost
     *
     * @param accountingcost the value for lg_cargodetails.accountingCost
     *
     * @mbggenerated
     */
    public void setAccountingcost(Double accountingcost) {
        this.accountingcost = accountingcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_cargodetails.receiptPerson
     *
     * @return the value of lg_cargodetails.receiptPerson
     *
     * @mbggenerated
     */
    public String getReceiptperson() {
        return receiptperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_cargodetails.receiptPerson
     *
     * @param receiptperson the value for lg_cargodetails.receiptPerson
     *
     * @mbggenerated
     */
    public void setReceiptperson(String receiptperson) {
        this.receiptperson = receiptperson == null ? null : receiptperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_cargodetails.remarks1
     *
     * @return the value of lg_cargodetails.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_cargodetails.remarks1
     *
     * @param remarks1 the value for lg_cargodetails.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_cargodetails.remarks2
     *
     * @return the value of lg_cargodetails.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_cargodetails.remarks2
     *
     * @param remarks2 the value for lg_cargodetails.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_cargodetails
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cargodetailsid=").append(cargodetailsid);
        sb.append(", predictedquantity=").append(predictedquantity);
        sb.append(", predictedvolume=").append(predictedvolume);
        sb.append(", predictedweight=").append(predictedweight);
        sb.append(", origingoodsid=").append(origingoodsid);
        sb.append(", arrivalgoodsid=").append(arrivalgoodsid);
        sb.append(", deliverymode=").append(deliverymode);
        sb.append(", accountingcost=").append(accountingcost);
        sb.append(", receiptperson=").append(receiptperson);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}