package cn.log.pojo;

import java.io.Serializable;

public class LgCarrier implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.carrierId
     *
     * @mbggenerated
     */
    private Integer carrierid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.carrierName
     *
     * @mbggenerated
     */
    private String carriername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.enterpriseNature
     *
     * @mbggenerated
     */
    private Integer enterprisenature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.enterprisePhone
     *
     * @mbggenerated
     */
    private String enterprisephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.enterpriseAddress
     *
     * @mbggenerated
     */
    private String enterpriseaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.registeredCapital
     *
     * @mbggenerated
     */
    private Double registeredcapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.corporateRepresentative
     *
     * @mbggenerated
     */
    private String corporaterepresentative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.businessLicenseNumber
     *
     * @mbggenerated
     */
    private String businesslicensenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.taxRegistrationNumber
     *
     * @mbggenerated
     */
    private String taxregistrationnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.roadTransportLicense
     *
     * @mbggenerated
     */
    private String roadtransportlicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.advantageLine
     *
     * @mbggenerated
     */
    private String advantageline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.cooperationState
     *
     * @mbggenerated
     */
    private Integer cooperationstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.affiliatedCompany
     *
     * @mbggenerated
     */
    private String affiliatedcompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.cardPicture
     *
     * @mbggenerated
     */
    private String cardpicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.businessLicensePictures
     *
     * @mbggenerated
     */
    private String businesslicensepictures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.roadTransportLicensePicture
     *
     * @mbggenerated
     */
    private String roadtransportlicensepicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.contractPicture
     *
     * @mbggenerated
     */
    private String contractpicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_carrier.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_carrier
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.carrierId
     *
     * @return the value of lg_carrier.carrierId
     *
     * @mbggenerated
     */
    public Integer getCarrierid() {
        return carrierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.carrierId
     *
     * @param carrierid the value for lg_carrier.carrierId
     *
     * @mbggenerated
     */
    public void setCarrierid(Integer carrierid) {
        this.carrierid = carrierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.carrierName
     *
     * @return the value of lg_carrier.carrierName
     *
     * @mbggenerated
     */
    public String getCarriername() {
        return carriername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.carrierName
     *
     * @param carriername the value for lg_carrier.carrierName
     *
     * @mbggenerated
     */
    public void setCarriername(String carriername) {
        this.carriername = carriername == null ? null : carriername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.enterpriseNature
     *
     * @return the value of lg_carrier.enterpriseNature
     *
     * @mbggenerated
     */
    public Integer getEnterprisenature() {
        return enterprisenature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.enterpriseNature
     *
     * @param enterprisenature the value for lg_carrier.enterpriseNature
     *
     * @mbggenerated
     */
    public void setEnterprisenature(Integer enterprisenature) {
        this.enterprisenature = enterprisenature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.enterprisePhone
     *
     * @return the value of lg_carrier.enterprisePhone
     *
     * @mbggenerated
     */
    public String getEnterprisephone() {
        return enterprisephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.enterprisePhone
     *
     * @param enterprisephone the value for lg_carrier.enterprisePhone
     *
     * @mbggenerated
     */
    public void setEnterprisephone(String enterprisephone) {
        this.enterprisephone = enterprisephone == null ? null : enterprisephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.enterpriseAddress
     *
     * @return the value of lg_carrier.enterpriseAddress
     *
     * @mbggenerated
     */
    public String getEnterpriseaddress() {
        return enterpriseaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.enterpriseAddress
     *
     * @param enterpriseaddress the value for lg_carrier.enterpriseAddress
     *
     * @mbggenerated
     */
    public void setEnterpriseaddress(String enterpriseaddress) {
        this.enterpriseaddress = enterpriseaddress == null ? null : enterpriseaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.registeredCapital
     *
     * @return the value of lg_carrier.registeredCapital
     *
     * @mbggenerated
     */
    public Double getRegisteredcapital() {
        return registeredcapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.registeredCapital
     *
     * @param registeredcapital the value for lg_carrier.registeredCapital
     *
     * @mbggenerated
     */
    public void setRegisteredcapital(Double registeredcapital) {
        this.registeredcapital = registeredcapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.corporateRepresentative
     *
     * @return the value of lg_carrier.corporateRepresentative
     *
     * @mbggenerated
     */
    public String getCorporaterepresentative() {
        return corporaterepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.corporateRepresentative
     *
     * @param corporaterepresentative the value for lg_carrier.corporateRepresentative
     *
     * @mbggenerated
     */
    public void setCorporaterepresentative(String corporaterepresentative) {
        this.corporaterepresentative = corporaterepresentative == null ? null : corporaterepresentative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.businessLicenseNumber
     *
     * @return the value of lg_carrier.businessLicenseNumber
     *
     * @mbggenerated
     */
    public String getBusinesslicensenumber() {
        return businesslicensenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.businessLicenseNumber
     *
     * @param businesslicensenumber the value for lg_carrier.businessLicenseNumber
     *
     * @mbggenerated
     */
    public void setBusinesslicensenumber(String businesslicensenumber) {
        this.businesslicensenumber = businesslicensenumber == null ? null : businesslicensenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.taxRegistrationNumber
     *
     * @return the value of lg_carrier.taxRegistrationNumber
     *
     * @mbggenerated
     */
    public String getTaxregistrationnumber() {
        return taxregistrationnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.taxRegistrationNumber
     *
     * @param taxregistrationnumber the value for lg_carrier.taxRegistrationNumber
     *
     * @mbggenerated
     */
    public void setTaxregistrationnumber(String taxregistrationnumber) {
        this.taxregistrationnumber = taxregistrationnumber == null ? null : taxregistrationnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.roadTransportLicense
     *
     * @return the value of lg_carrier.roadTransportLicense
     *
     * @mbggenerated
     */
    public String getRoadtransportlicense() {
        return roadtransportlicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.roadTransportLicense
     *
     * @param roadtransportlicense the value for lg_carrier.roadTransportLicense
     *
     * @mbggenerated
     */
    public void setRoadtransportlicense(String roadtransportlicense) {
        this.roadtransportlicense = roadtransportlicense == null ? null : roadtransportlicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.advantageLine
     *
     * @return the value of lg_carrier.advantageLine
     *
     * @mbggenerated
     */
    public String getAdvantageline() {
        return advantageline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.advantageLine
     *
     * @param advantageline the value for lg_carrier.advantageLine
     *
     * @mbggenerated
     */
    public void setAdvantageline(String advantageline) {
        this.advantageline = advantageline == null ? null : advantageline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.cooperationState
     *
     * @return the value of lg_carrier.cooperationState
     *
     * @mbggenerated
     */
    public Integer getCooperationstate() {
        return cooperationstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.cooperationState
     *
     * @param cooperationstate the value for lg_carrier.cooperationState
     *
     * @mbggenerated
     */
    public void setCooperationstate(Integer cooperationstate) {
        this.cooperationstate = cooperationstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.affiliatedCompany
     *
     * @return the value of lg_carrier.affiliatedCompany
     *
     * @mbggenerated
     */
    public String getAffiliatedcompany() {
        return affiliatedcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.affiliatedCompany
     *
     * @param affiliatedcompany the value for lg_carrier.affiliatedCompany
     *
     * @mbggenerated
     */
    public void setAffiliatedcompany(String affiliatedcompany) {
        this.affiliatedcompany = affiliatedcompany == null ? null : affiliatedcompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.cardPicture
     *
     * @return the value of lg_carrier.cardPicture
     *
     * @mbggenerated
     */
    public String getCardpicture() {
        return cardpicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.cardPicture
     *
     * @param cardpicture the value for lg_carrier.cardPicture
     *
     * @mbggenerated
     */
    public void setCardpicture(String cardpicture) {
        this.cardpicture = cardpicture == null ? null : cardpicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.businessLicensePictures
     *
     * @return the value of lg_carrier.businessLicensePictures
     *
     * @mbggenerated
     */
    public String getBusinesslicensepictures() {
        return businesslicensepictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.businessLicensePictures
     *
     * @param businesslicensepictures the value for lg_carrier.businessLicensePictures
     *
     * @mbggenerated
     */
    public void setBusinesslicensepictures(String businesslicensepictures) {
        this.businesslicensepictures = businesslicensepictures == null ? null : businesslicensepictures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.roadTransportLicensePicture
     *
     * @return the value of lg_carrier.roadTransportLicensePicture
     *
     * @mbggenerated
     */
    public String getRoadtransportlicensepicture() {
        return roadtransportlicensepicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.roadTransportLicensePicture
     *
     * @param roadtransportlicensepicture the value for lg_carrier.roadTransportLicensePicture
     *
     * @mbggenerated
     */
    public void setRoadtransportlicensepicture(String roadtransportlicensepicture) {
        this.roadtransportlicensepicture = roadtransportlicensepicture == null ? null : roadtransportlicensepicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.contractPicture
     *
     * @return the value of lg_carrier.contractPicture
     *
     * @mbggenerated
     */
    public String getContractpicture() {
        return contractpicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.contractPicture
     *
     * @param contractpicture the value for lg_carrier.contractPicture
     *
     * @mbggenerated
     */
    public void setContractpicture(String contractpicture) {
        this.contractpicture = contractpicture == null ? null : contractpicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.remarks1
     *
     * @return the value of lg_carrier.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.remarks1
     *
     * @param remarks1 the value for lg_carrier.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_carrier.remarks2
     *
     * @return the value of lg_carrier.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_carrier.remarks2
     *
     * @param remarks2 the value for lg_carrier.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_carrier
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", carrierid=").append(carrierid);
        sb.append(", carriername=").append(carriername);
        sb.append(", enterprisenature=").append(enterprisenature);
        sb.append(", enterprisephone=").append(enterprisephone);
        sb.append(", enterpriseaddress=").append(enterpriseaddress);
        sb.append(", registeredcapital=").append(registeredcapital);
        sb.append(", corporaterepresentative=").append(corporaterepresentative);
        sb.append(", businesslicensenumber=").append(businesslicensenumber);
        sb.append(", taxregistrationnumber=").append(taxregistrationnumber);
        sb.append(", roadtransportlicense=").append(roadtransportlicense);
        sb.append(", advantageline=").append(advantageline);
        sb.append(", cooperationstate=").append(cooperationstate);
        sb.append(", affiliatedcompany=").append(affiliatedcompany);
        sb.append(", cardpicture=").append(cardpicture);
        sb.append(", businesslicensepictures=").append(businesslicensepictures);
        sb.append(", roadtransportlicensepicture=").append(roadtransportlicensepicture);
        sb.append(", contractpicture=").append(contractpicture);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}