package cn.log.pojo;

import java.io.Serializable;

public class LgCompensationgoodsorder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_compensationgoodsorder.compensationId
     *
     * @mbggenerated
     */
    private Integer compensationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_compensationgoodsorder.compensationGoodsId
     *
     * @mbggenerated
     */
    private Integer compensationgoodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_compensationgoodsorder.orderId
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_compensationgoodsorder.warehousingQuantity
     *
     * @mbggenerated
     */
    private Integer warehousingquantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_compensationgoodsorder
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_compensationgoodsorder.compensationId
     *
     * @return the value of lg_compensationgoodsorder.compensationId
     *
     * @mbggenerated
     */
    public Integer getCompensationid() {
        return compensationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_compensationgoodsorder.compensationId
     *
     * @param compensationid the value for lg_compensationgoodsorder.compensationId
     *
     * @mbggenerated
     */
    public void setCompensationid(Integer compensationid) {
        this.compensationid = compensationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_compensationgoodsorder.compensationGoodsId
     *
     * @return the value of lg_compensationgoodsorder.compensationGoodsId
     *
     * @mbggenerated
     */
    public Integer getCompensationgoodsid() {
        return compensationgoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_compensationgoodsorder.compensationGoodsId
     *
     * @param compensationgoodsid the value for lg_compensationgoodsorder.compensationGoodsId
     *
     * @mbggenerated
     */
    public void setCompensationgoodsid(Integer compensationgoodsid) {
        this.compensationgoodsid = compensationgoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_compensationgoodsorder.orderId
     *
     * @return the value of lg_compensationgoodsorder.orderId
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_compensationgoodsorder.orderId
     *
     * @param orderid the value for lg_compensationgoodsorder.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_compensationgoodsorder.warehousingQuantity
     *
     * @return the value of lg_compensationgoodsorder.warehousingQuantity
     *
     * @mbggenerated
     */
    public Integer getWarehousingquantity() {
        return warehousingquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_compensationgoodsorder.warehousingQuantity
     *
     * @param warehousingquantity the value for lg_compensationgoodsorder.warehousingQuantity
     *
     * @mbggenerated
     */
    public void setWarehousingquantity(Integer warehousingquantity) {
        this.warehousingquantity = warehousingquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_compensationgoodsorder
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", compensationid=").append(compensationid);
        sb.append(", compensationgoodsid=").append(compensationgoodsid);
        sb.append(", orderid=").append(orderid);
        sb.append(", warehousingquantity=").append(warehousingquantity);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}