package cn.log.pojo;

import java.io.Serializable;
import java.util.Date;

public class LgDriver implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.driverId
     *
     * @mbggenerated
     */
    private Integer driverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.driverName
     *
     * @mbggenerated
     */
    private String drivername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.idCard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.nativePlace
     *
     * @mbggenerated
     */
    private String nativeplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.entryTime
     *
     * @mbggenerated
     */
    private Date entrytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.departureTime
     *
     * @mbggenerated
     */
    private Date departuretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.affiliatedCompanyId
     *
     * @mbggenerated
     */
    private Integer affiliatedcompanyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.driverStatus
     *
     * @mbggenerated
     */
    private String driverstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.idCardPicture
     *
     * @mbggenerated
     */
    private String idcardpicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.driverLicensePicture
     *
     * @mbggenerated
     */
    private String driverlicensepicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.fromLicensePicture
     *
     * @mbggenerated
     */
    private String fromlicensepicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_driver.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_driver
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.driverId
     *
     * @return the value of lg_driver.driverId
     *
     * @mbggenerated
     */
    public Integer getDriverid() {
        return driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.driverId
     *
     * @param driverid the value for lg_driver.driverId
     *
     * @mbggenerated
     */
    public void setDriverid(Integer driverid) {
        this.driverid = driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.driverName
     *
     * @return the value of lg_driver.driverName
     *
     * @mbggenerated
     */
    public String getDrivername() {
        return drivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.driverName
     *
     * @param drivername the value for lg_driver.driverName
     *
     * @mbggenerated
     */
    public void setDrivername(String drivername) {
        this.drivername = drivername == null ? null : drivername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.idCard
     *
     * @return the value of lg_driver.idCard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.idCard
     *
     * @param idcard the value for lg_driver.idCard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.gender
     *
     * @return the value of lg_driver.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.gender
     *
     * @param gender the value for lg_driver.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.nativePlace
     *
     * @return the value of lg_driver.nativePlace
     *
     * @mbggenerated
     */
    public String getNativeplace() {
        return nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.nativePlace
     *
     * @param nativeplace the value for lg_driver.nativePlace
     *
     * @mbggenerated
     */
    public void setNativeplace(String nativeplace) {
        this.nativeplace = nativeplace == null ? null : nativeplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.birthday
     *
     * @return the value of lg_driver.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.birthday
     *
     * @param birthday the value for lg_driver.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.phone
     *
     * @return the value of lg_driver.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.phone
     *
     * @param phone the value for lg_driver.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.address
     *
     * @return the value of lg_driver.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.address
     *
     * @param address the value for lg_driver.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.entryTime
     *
     * @return the value of lg_driver.entryTime
     *
     * @mbggenerated
     */
    public Date getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.entryTime
     *
     * @param entrytime the value for lg_driver.entryTime
     *
     * @mbggenerated
     */
    public void setEntrytime(Date entrytime) {
        this.entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.departureTime
     *
     * @return the value of lg_driver.departureTime
     *
     * @mbggenerated
     */
    public Date getDeparturetime() {
        return departuretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.departureTime
     *
     * @param departuretime the value for lg_driver.departureTime
     *
     * @mbggenerated
     */
    public void setDeparturetime(Date departuretime) {
        this.departuretime = departuretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.affiliatedCompanyId
     *
     * @return the value of lg_driver.affiliatedCompanyId
     *
     * @mbggenerated
     */
    public Integer getAffiliatedcompanyid() {
        return affiliatedcompanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.affiliatedCompanyId
     *
     * @param affiliatedcompanyid the value for lg_driver.affiliatedCompanyId
     *
     * @mbggenerated
     */
    public void setAffiliatedcompanyid(Integer affiliatedcompanyid) {
        this.affiliatedcompanyid = affiliatedcompanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.driverStatus
     *
     * @return the value of lg_driver.driverStatus
     *
     * @mbggenerated
     */
    public String getDriverstatus() {
        return driverstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.driverStatus
     *
     * @param driverstatus the value for lg_driver.driverStatus
     *
     * @mbggenerated
     */
    public void setDriverstatus(String driverstatus) {
        this.driverstatus = driverstatus == null ? null : driverstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.remarks
     *
     * @return the value of lg_driver.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.remarks
     *
     * @param remarks the value for lg_driver.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.idCardPicture
     *
     * @return the value of lg_driver.idCardPicture
     *
     * @mbggenerated
     */
    public String getIdcardpicture() {
        return idcardpicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.idCardPicture
     *
     * @param idcardpicture the value for lg_driver.idCardPicture
     *
     * @mbggenerated
     */
    public void setIdcardpicture(String idcardpicture) {
        this.idcardpicture = idcardpicture == null ? null : idcardpicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.driverLicensePicture
     *
     * @return the value of lg_driver.driverLicensePicture
     *
     * @mbggenerated
     */
    public String getDriverlicensepicture() {
        return driverlicensepicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.driverLicensePicture
     *
     * @param driverlicensepicture the value for lg_driver.driverLicensePicture
     *
     * @mbggenerated
     */
    public void setDriverlicensepicture(String driverlicensepicture) {
        this.driverlicensepicture = driverlicensepicture == null ? null : driverlicensepicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.fromLicensePicture
     *
     * @return the value of lg_driver.fromLicensePicture
     *
     * @mbggenerated
     */
    public String getFromlicensepicture() {
        return fromlicensepicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.fromLicensePicture
     *
     * @param fromlicensepicture the value for lg_driver.fromLicensePicture
     *
     * @mbggenerated
     */
    public void setFromlicensepicture(String fromlicensepicture) {
        this.fromlicensepicture = fromlicensepicture == null ? null : fromlicensepicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.remarks1
     *
     * @return the value of lg_driver.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.remarks1
     *
     * @param remarks1 the value for lg_driver.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_driver.remarks2
     *
     * @return the value of lg_driver.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_driver.remarks2
     *
     * @param remarks2 the value for lg_driver.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_driver
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", driverid=").append(driverid);
        sb.append(", drivername=").append(drivername);
        sb.append(", idcard=").append(idcard);
        sb.append(", gender=").append(gender);
        sb.append(", nativeplace=").append(nativeplace);
        sb.append(", birthday=").append(birthday);
        sb.append(", phone=").append(phone);
        sb.append(", address=").append(address);
        sb.append(", entrytime=").append(entrytime);
        sb.append(", departuretime=").append(departuretime);
        sb.append(", affiliatedcompanyid=").append(affiliatedcompanyid);
        sb.append(", driverstatus=").append(driverstatus);
        sb.append(", remarks=").append(remarks);
        sb.append(", idcardpicture=").append(idcardpicture);
        sb.append(", driverlicensepicture=").append(driverlicensepicture);
        sb.append(", fromlicensepicture=").append(fromlicensepicture);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}