package cn.log.pojo;

import java.io.Serializable;
import java.util.Date;

public class LgEtrustmentslip implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_etrustmentslip.entrustmentSlipId
     *
     * @mbggenerated
     */
    private Integer entrustmentslipid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_etrustmentslip.vehicleNumber
     *
     * @mbggenerated
     */
    private Integer vehiclenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_etrustmentslip.damagedDeduction
     *
     * @mbggenerated
     */
    private Double damageddeduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_etrustmentslip.carserviceDeduction
     *
     * @mbggenerated
     */
    private Double carservicededuction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_etrustmentslip.creatDate
     *
     * @mbggenerated
     */
    private Date creatdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_etrustmentslip.wayBillId
     *
     * @mbggenerated
     */
    private Integer waybillid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_etrustmentslip.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_etrustmentslip.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_etrustmentslip
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_etrustmentslip.entrustmentSlipId
     *
     * @return the value of lg_etrustmentslip.entrustmentSlipId
     *
     * @mbggenerated
     */
    public Integer getEntrustmentslipid() {
        return entrustmentslipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_etrustmentslip.entrustmentSlipId
     *
     * @param entrustmentslipid the value for lg_etrustmentslip.entrustmentSlipId
     *
     * @mbggenerated
     */
    public void setEntrustmentslipid(Integer entrustmentslipid) {
        this.entrustmentslipid = entrustmentslipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_etrustmentslip.vehicleNumber
     *
     * @return the value of lg_etrustmentslip.vehicleNumber
     *
     * @mbggenerated
     */
    public Integer getVehiclenumber() {
        return vehiclenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_etrustmentslip.vehicleNumber
     *
     * @param vehiclenumber the value for lg_etrustmentslip.vehicleNumber
     *
     * @mbggenerated
     */
    public void setVehiclenumber(Integer vehiclenumber) {
        this.vehiclenumber = vehiclenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_etrustmentslip.damagedDeduction
     *
     * @return the value of lg_etrustmentslip.damagedDeduction
     *
     * @mbggenerated
     */
    public Double getDamageddeduction() {
        return damageddeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_etrustmentslip.damagedDeduction
     *
     * @param damageddeduction the value for lg_etrustmentslip.damagedDeduction
     *
     * @mbggenerated
     */
    public void setDamageddeduction(Double damageddeduction) {
        this.damageddeduction = damageddeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_etrustmentslip.carserviceDeduction
     *
     * @return the value of lg_etrustmentslip.carserviceDeduction
     *
     * @mbggenerated
     */
    public Double getCarservicededuction() {
        return carservicededuction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_etrustmentslip.carserviceDeduction
     *
     * @param carservicededuction the value for lg_etrustmentslip.carserviceDeduction
     *
     * @mbggenerated
     */
    public void setCarservicededuction(Double carservicededuction) {
        this.carservicededuction = carservicededuction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_etrustmentslip.creatDate
     *
     * @return the value of lg_etrustmentslip.creatDate
     *
     * @mbggenerated
     */
    public Date getCreatdate() {
        return creatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_etrustmentslip.creatDate
     *
     * @param creatdate the value for lg_etrustmentslip.creatDate
     *
     * @mbggenerated
     */
    public void setCreatdate(Date creatdate) {
        this.creatdate = creatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_etrustmentslip.wayBillId
     *
     * @return the value of lg_etrustmentslip.wayBillId
     *
     * @mbggenerated
     */
    public Integer getWaybillid() {
        return waybillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_etrustmentslip.wayBillId
     *
     * @param waybillid the value for lg_etrustmentslip.wayBillId
     *
     * @mbggenerated
     */
    public void setWaybillid(Integer waybillid) {
        this.waybillid = waybillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_etrustmentslip.remarks1
     *
     * @return the value of lg_etrustmentslip.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_etrustmentslip.remarks1
     *
     * @param remarks1 the value for lg_etrustmentslip.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_etrustmentslip.remarks2
     *
     * @return the value of lg_etrustmentslip.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_etrustmentslip.remarks2
     *
     * @param remarks2 the value for lg_etrustmentslip.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_etrustmentslip
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", entrustmentslipid=").append(entrustmentslipid);
        sb.append(", vehiclenumber=").append(vehiclenumber);
        sb.append(", damageddeduction=").append(damageddeduction);
        sb.append(", carservicededuction=").append(carservicededuction);
        sb.append(", creatdate=").append(creatdate);
        sb.append(", waybillid=").append(waybillid);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}