package cn.log.pojo;

import java.io.Serializable;

public class LgFreightcharges implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_freightcharges.freightChargesId
     *
     * @mbggenerated
     */
    private Integer freightchargesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_freightcharges.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_freightcharges.goosTypeAttribute
     *
     * @mbggenerated
     */
    private Integer goostypeattribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_freightcharges.minDistance
     *
     * @mbggenerated
     */
    private Double mindistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_freightcharges.maxDistance
     *
     * @mbggenerated
     */
    private Double maxdistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_freightcharges.minVolume
     *
     * @mbggenerated
     */
    private Double minvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_freightcharges.maxVolume
     *
     * @mbggenerated
     */
    private Double maxvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_freightcharges.minWeight
     *
     * @mbggenerated
     */
    private Double minweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_freightcharges.maxWeight
     *
     * @mbggenerated
     */
    private Double maxweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_freightcharges.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_freightcharges.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_freightcharges
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_freightcharges.freightChargesId
     *
     * @return the value of lg_freightcharges.freightChargesId
     *
     * @mbggenerated
     */
    public Integer getFreightchargesid() {
        return freightchargesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_freightcharges.freightChargesId
     *
     * @param freightchargesid the value for lg_freightcharges.freightChargesId
     *
     * @mbggenerated
     */
    public void setFreightchargesid(Integer freightchargesid) {
        this.freightchargesid = freightchargesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_freightcharges.price
     *
     * @return the value of lg_freightcharges.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_freightcharges.price
     *
     * @param price the value for lg_freightcharges.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_freightcharges.goosTypeAttribute
     *
     * @return the value of lg_freightcharges.goosTypeAttribute
     *
     * @mbggenerated
     */
    public Integer getGoostypeattribute() {
        return goostypeattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_freightcharges.goosTypeAttribute
     *
     * @param goostypeattribute the value for lg_freightcharges.goosTypeAttribute
     *
     * @mbggenerated
     */
    public void setGoostypeattribute(Integer goostypeattribute) {
        this.goostypeattribute = goostypeattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_freightcharges.minDistance
     *
     * @return the value of lg_freightcharges.minDistance
     *
     * @mbggenerated
     */
    public Double getMindistance() {
        return mindistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_freightcharges.minDistance
     *
     * @param mindistance the value for lg_freightcharges.minDistance
     *
     * @mbggenerated
     */
    public void setMindistance(Double mindistance) {
        this.mindistance = mindistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_freightcharges.maxDistance
     *
     * @return the value of lg_freightcharges.maxDistance
     *
     * @mbggenerated
     */
    public Double getMaxdistance() {
        return maxdistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_freightcharges.maxDistance
     *
     * @param maxdistance the value for lg_freightcharges.maxDistance
     *
     * @mbggenerated
     */
    public void setMaxdistance(Double maxdistance) {
        this.maxdistance = maxdistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_freightcharges.minVolume
     *
     * @return the value of lg_freightcharges.minVolume
     *
     * @mbggenerated
     */
    public Double getMinvolume() {
        return minvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_freightcharges.minVolume
     *
     * @param minvolume the value for lg_freightcharges.minVolume
     *
     * @mbggenerated
     */
    public void setMinvolume(Double minvolume) {
        this.minvolume = minvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_freightcharges.maxVolume
     *
     * @return the value of lg_freightcharges.maxVolume
     *
     * @mbggenerated
     */
    public Double getMaxvolume() {
        return maxvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_freightcharges.maxVolume
     *
     * @param maxvolume the value for lg_freightcharges.maxVolume
     *
     * @mbggenerated
     */
    public void setMaxvolume(Double maxvolume) {
        this.maxvolume = maxvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_freightcharges.minWeight
     *
     * @return the value of lg_freightcharges.minWeight
     *
     * @mbggenerated
     */
    public Double getMinweight() {
        return minweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_freightcharges.minWeight
     *
     * @param minweight the value for lg_freightcharges.minWeight
     *
     * @mbggenerated
     */
    public void setMinweight(Double minweight) {
        this.minweight = minweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_freightcharges.maxWeight
     *
     * @return the value of lg_freightcharges.maxWeight
     *
     * @mbggenerated
     */
    public Double getMaxweight() {
        return maxweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_freightcharges.maxWeight
     *
     * @param maxweight the value for lg_freightcharges.maxWeight
     *
     * @mbggenerated
     */
    public void setMaxweight(Double maxweight) {
        this.maxweight = maxweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_freightcharges.remarks1
     *
     * @return the value of lg_freightcharges.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_freightcharges.remarks1
     *
     * @param remarks1 the value for lg_freightcharges.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_freightcharges.remarks2
     *
     * @return the value of lg_freightcharges.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_freightcharges.remarks2
     *
     * @param remarks2 the value for lg_freightcharges.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_freightcharges
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", freightchargesid=").append(freightchargesid);
        sb.append(", price=").append(price);
        sb.append(", goostypeattribute=").append(goostypeattribute);
        sb.append(", mindistance=").append(mindistance);
        sb.append(", maxdistance=").append(maxdistance);
        sb.append(", minvolume=").append(minvolume);
        sb.append(", maxvolume=").append(maxvolume);
        sb.append(", minweight=").append(minweight);
        sb.append(", maxweight=").append(maxweight);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}