package cn.log.pojo;

import java.io.Serializable;
import java.util.Date;

public class LgGoodsdamage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_goodsdamage.goodsDamageId
     *
     * @mbggenerated
     */
    private Integer goodsdamageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_goodsdamage.goodsId
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_goodsdamage.amount
     *
     * @mbggenerated
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_goodsdamage.entryTime
     *
     * @mbggenerated
     */
    private Date entrytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_goodsdamage.storekeeperId
     *
     * @mbggenerated
     */
    private Integer storekeeperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_goodsdamage.outgoing
     *
     * @mbggenerated
     */
    private Integer outgoing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_goodsdamage.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_goodsdamage.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_goodsdamage.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_goodsdamage
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_goodsdamage.goodsDamageId
     *
     * @return the value of lg_goodsdamage.goodsDamageId
     *
     * @mbggenerated
     */
    public Integer getGoodsdamageid() {
        return goodsdamageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_goodsdamage.goodsDamageId
     *
     * @param goodsdamageid the value for lg_goodsdamage.goodsDamageId
     *
     * @mbggenerated
     */
    public void setGoodsdamageid(Integer goodsdamageid) {
        this.goodsdamageid = goodsdamageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_goodsdamage.goodsId
     *
     * @return the value of lg_goodsdamage.goodsId
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_goodsdamage.goodsId
     *
     * @param goodsid the value for lg_goodsdamage.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_goodsdamage.amount
     *
     * @return the value of lg_goodsdamage.amount
     *
     * @mbggenerated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_goodsdamage.amount
     *
     * @param amount the value for lg_goodsdamage.amount
     *
     * @mbggenerated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_goodsdamage.entryTime
     *
     * @return the value of lg_goodsdamage.entryTime
     *
     * @mbggenerated
     */
    public Date getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_goodsdamage.entryTime
     *
     * @param entrytime the value for lg_goodsdamage.entryTime
     *
     * @mbggenerated
     */
    public void setEntrytime(Date entrytime) {
        this.entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_goodsdamage.storekeeperId
     *
     * @return the value of lg_goodsdamage.storekeeperId
     *
     * @mbggenerated
     */
    public Integer getStorekeeperid() {
        return storekeeperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_goodsdamage.storekeeperId
     *
     * @param storekeeperid the value for lg_goodsdamage.storekeeperId
     *
     * @mbggenerated
     */
    public void setStorekeeperid(Integer storekeeperid) {
        this.storekeeperid = storekeeperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_goodsdamage.outgoing
     *
     * @return the value of lg_goodsdamage.outgoing
     *
     * @mbggenerated
     */
    public Integer getOutgoing() {
        return outgoing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_goodsdamage.outgoing
     *
     * @param outgoing the value for lg_goodsdamage.outgoing
     *
     * @mbggenerated
     */
    public void setOutgoing(Integer outgoing) {
        this.outgoing = outgoing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_goodsdamage.remarks
     *
     * @return the value of lg_goodsdamage.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_goodsdamage.remarks
     *
     * @param remarks the value for lg_goodsdamage.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_goodsdamage.remarks1
     *
     * @return the value of lg_goodsdamage.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_goodsdamage.remarks1
     *
     * @param remarks1 the value for lg_goodsdamage.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_goodsdamage.remarks2
     *
     * @return the value of lg_goodsdamage.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_goodsdamage.remarks2
     *
     * @param remarks2 the value for lg_goodsdamage.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_goodsdamage
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", goodsdamageid=").append(goodsdamageid);
        sb.append(", goodsid=").append(goodsid);
        sb.append(", amount=").append(amount);
        sb.append(", entrytime=").append(entrytime);
        sb.append(", storekeeperid=").append(storekeeperid);
        sb.append(", outgoing=").append(outgoing);
        sb.append(", remarks=").append(remarks);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}