package cn.log.pojo;

import java.io.Serializable;

public class LgGoodstypecharges implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_goodstypecharges.goodsTypeId
     *
     * @mbggenerated
     */
    private Integer goodstypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_goodstypecharges.freightChargesId
     *
     * @mbggenerated
     */
    private Integer freightchargesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_goodstypecharges
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_goodstypecharges.goodsTypeId
     *
     * @return the value of lg_goodstypecharges.goodsTypeId
     *
     * @mbggenerated
     */
    public Integer getGoodstypeid() {
        return goodstypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_goodstypecharges.goodsTypeId
     *
     * @param goodstypeid the value for lg_goodstypecharges.goodsTypeId
     *
     * @mbggenerated
     */
    public void setGoodstypeid(Integer goodstypeid) {
        this.goodstypeid = goodstypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_goodstypecharges.freightChargesId
     *
     * @return the value of lg_goodstypecharges.freightChargesId
     *
     * @mbggenerated
     */
    public Integer getFreightchargesid() {
        return freightchargesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_goodstypecharges.freightChargesId
     *
     * @param freightchargesid the value for lg_goodstypecharges.freightChargesId
     *
     * @mbggenerated
     */
    public void setFreightchargesid(Integer freightchargesid) {
        this.freightchargesid = freightchargesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_goodstypecharges
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", goodstypeid=").append(goodstypeid);
        sb.append(", freightchargesid=").append(freightchargesid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}