package cn.log.pojo;

import java.io.Serializable;
import java.util.Date;

public class LgIncome implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_income.incomeId
     *
     * @mbggenerated
     */
    private Integer incomeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_income.incomeAmount
     *
     * @mbggenerated
     */
    private Double incomeamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_income.incomeRemarks
     *
     * @mbggenerated
     */
    private String incomeremarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_income.incomeTime
     *
     * @mbggenerated
     */
    private Date incometime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_income.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_income.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_income
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_income.incomeId
     *
     * @return the value of lg_income.incomeId
     *
     * @mbggenerated
     */
    public Integer getIncomeid() {
        return incomeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_income.incomeId
     *
     * @param incomeid the value for lg_income.incomeId
     *
     * @mbggenerated
     */
    public void setIncomeid(Integer incomeid) {
        this.incomeid = incomeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_income.incomeAmount
     *
     * @return the value of lg_income.incomeAmount
     *
     * @mbggenerated
     */
    public Double getIncomeamount() {
        return incomeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_income.incomeAmount
     *
     * @param incomeamount the value for lg_income.incomeAmount
     *
     * @mbggenerated
     */
    public void setIncomeamount(Double incomeamount) {
        this.incomeamount = incomeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_income.incomeRemarks
     *
     * @return the value of lg_income.incomeRemarks
     *
     * @mbggenerated
     */
    public String getIncomeremarks() {
        return incomeremarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_income.incomeRemarks
     *
     * @param incomeremarks the value for lg_income.incomeRemarks
     *
     * @mbggenerated
     */
    public void setIncomeremarks(String incomeremarks) {
        this.incomeremarks = incomeremarks == null ? null : incomeremarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_income.incomeTime
     *
     * @return the value of lg_income.incomeTime
     *
     * @mbggenerated
     */
    public Date getIncometime() {
        return incometime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_income.incomeTime
     *
     * @param incometime the value for lg_income.incomeTime
     *
     * @mbggenerated
     */
    public void setIncometime(Date incometime) {
        this.incometime = incometime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_income.remarks1
     *
     * @return the value of lg_income.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_income.remarks1
     *
     * @param remarks1 the value for lg_income.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_income.remarks2
     *
     * @return the value of lg_income.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_income.remarks2
     *
     * @param remarks2 the value for lg_income.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_income
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", incomeid=").append(incomeid);
        sb.append(", incomeamount=").append(incomeamount);
        sb.append(", incomeremarks=").append(incomeremarks);
        sb.append(", incometime=").append(incometime);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}