package cn.log.pojo;

import java.io.Serializable;
import java.util.Date;

public class LgOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.orderId
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.shipperId
     *
     * @mbggenerated
     */
    private Integer shipperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.receivingPartyId
     *
     * @mbggenerated
     */
    private Integer receivingpartyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.originatingPlace
     *
     * @mbggenerated
     */
    private String originatingplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.destination
     *
     * @mbggenerated
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.deliveryTime
     *
     * @mbggenerated
     */
    private Date deliverytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.deliveryMode
     *
     * @mbggenerated
     */
    private Integer deliverymode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.prescriptioRequirement
     *
     * @mbggenerated
     */
    private String prescriptiorequirement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.totalNumber
     *
     * @mbggenerated
     */
    private Integer totalnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.orderVolume
     *
     * @mbggenerated
     */
    private Double ordervolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.totalWeight
     *
     * @mbggenerated
     */
    private Double totalweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.billingQuantity
     *
     * @mbggenerated
     */
    private Integer billingquantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.billingVolume
     *
     * @mbggenerated
     */
    private Double billingvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.billingWeight
     *
     * @mbggenerated
     */
    private Double billingweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.shippingType
     *
     * @mbggenerated
     */
    private Integer shippingtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.vehicleType
     *
     * @mbggenerated
     */
    private Integer vehicletype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.valueGoods
     *
     * @mbggenerated
     */
    private Double valuegoods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.affiliatedCompanyId
     *
     * @mbggenerated
     */
    private Integer affiliatedcompanyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.orderFreight
     *
     * @mbggenerated
     */
    private Double orderfreight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.pickupCharge
     *
     * @mbggenerated
     */
    private Double pickupcharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.deliverFee
     *
     * @mbggenerated
     */
    private Double deliverfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.insurancePremium
     *
     * @mbggenerated
     */
    private Double insurancepremium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.handlingCharges
     *
     * @mbggenerated
     */
    private Double handlingcharges;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.otherExpenses
     *
     * @mbggenerated
     */
    private Double otherexpenses;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.settlementMethod
     *
     * @mbggenerated
     */
    private Integer settlementmethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.collectionAmount
     *
     * @mbggenerated
     */
    private Double collectionamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.advanceCollection
     *
     * @mbggenerated
     */
    private Double advancecollection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.receivableLiablePerson
     *
     * @mbggenerated
     */
    private String receivableliableperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.receivableCompany
     *
     * @mbggenerated
     */
    private String receivablecompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.orderStatus
     *
     * @mbggenerated
     */
    private Integer orderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_order.orderType
     *
     * @mbggenerated
     */
    private Integer ordertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.orderId
     *
     * @return the value of lg_order.orderId
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.orderId
     *
     * @param orderid the value for lg_order.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.shipperId
     *
     * @return the value of lg_order.shipperId
     *
     * @mbggenerated
     */
    public Integer getShipperid() {
        return shipperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.shipperId
     *
     * @param shipperid the value for lg_order.shipperId
     *
     * @mbggenerated
     */
    public void setShipperid(Integer shipperid) {
        this.shipperid = shipperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.receivingPartyId
     *
     * @return the value of lg_order.receivingPartyId
     *
     * @mbggenerated
     */
    public Integer getReceivingpartyid() {
        return receivingpartyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.receivingPartyId
     *
     * @param receivingpartyid the value for lg_order.receivingPartyId
     *
     * @mbggenerated
     */
    public void setReceivingpartyid(Integer receivingpartyid) {
        this.receivingpartyid = receivingpartyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.originatingPlace
     *
     * @return the value of lg_order.originatingPlace
     *
     * @mbggenerated
     */
    public String getOriginatingplace() {
        return originatingplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.originatingPlace
     *
     * @param originatingplace the value for lg_order.originatingPlace
     *
     * @mbggenerated
     */
    public void setOriginatingplace(String originatingplace) {
        this.originatingplace = originatingplace == null ? null : originatingplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.destination
     *
     * @return the value of lg_order.destination
     *
     * @mbggenerated
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.destination
     *
     * @param destination the value for lg_order.destination
     *
     * @mbggenerated
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.deliveryTime
     *
     * @return the value of lg_order.deliveryTime
     *
     * @mbggenerated
     */
    public Date getDeliverytime() {
        return deliverytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.deliveryTime
     *
     * @param deliverytime the value for lg_order.deliveryTime
     *
     * @mbggenerated
     */
    public void setDeliverytime(Date deliverytime) {
        this.deliverytime = deliverytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.deliveryMode
     *
     * @return the value of lg_order.deliveryMode
     *
     * @mbggenerated
     */
    public Integer getDeliverymode() {
        return deliverymode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.deliveryMode
     *
     * @param deliverymode the value for lg_order.deliveryMode
     *
     * @mbggenerated
     */
    public void setDeliverymode(Integer deliverymode) {
        this.deliverymode = deliverymode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.prescriptioRequirement
     *
     * @return the value of lg_order.prescriptioRequirement
     *
     * @mbggenerated
     */
    public String getPrescriptiorequirement() {
        return prescriptiorequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.prescriptioRequirement
     *
     * @param prescriptiorequirement the value for lg_order.prescriptioRequirement
     *
     * @mbggenerated
     */
    public void setPrescriptiorequirement(String prescriptiorequirement) {
        this.prescriptiorequirement = prescriptiorequirement == null ? null : prescriptiorequirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.totalNumber
     *
     * @return the value of lg_order.totalNumber
     *
     * @mbggenerated
     */
    public Integer getTotalnumber() {
        return totalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.totalNumber
     *
     * @param totalnumber the value for lg_order.totalNumber
     *
     * @mbggenerated
     */
    public void setTotalnumber(Integer totalnumber) {
        this.totalnumber = totalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.orderVolume
     *
     * @return the value of lg_order.orderVolume
     *
     * @mbggenerated
     */
    public Double getOrdervolume() {
        return ordervolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.orderVolume
     *
     * @param ordervolume the value for lg_order.orderVolume
     *
     * @mbggenerated
     */
    public void setOrdervolume(Double ordervolume) {
        this.ordervolume = ordervolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.totalWeight
     *
     * @return the value of lg_order.totalWeight
     *
     * @mbggenerated
     */
    public Double getTotalweight() {
        return totalweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.totalWeight
     *
     * @param totalweight the value for lg_order.totalWeight
     *
     * @mbggenerated
     */
    public void setTotalweight(Double totalweight) {
        this.totalweight = totalweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.billingQuantity
     *
     * @return the value of lg_order.billingQuantity
     *
     * @mbggenerated
     */
    public Integer getBillingquantity() {
        return billingquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.billingQuantity
     *
     * @param billingquantity the value for lg_order.billingQuantity
     *
     * @mbggenerated
     */
    public void setBillingquantity(Integer billingquantity) {
        this.billingquantity = billingquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.billingVolume
     *
     * @return the value of lg_order.billingVolume
     *
     * @mbggenerated
     */
    public Double getBillingvolume() {
        return billingvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.billingVolume
     *
     * @param billingvolume the value for lg_order.billingVolume
     *
     * @mbggenerated
     */
    public void setBillingvolume(Double billingvolume) {
        this.billingvolume = billingvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.billingWeight
     *
     * @return the value of lg_order.billingWeight
     *
     * @mbggenerated
     */
    public Double getBillingweight() {
        return billingweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.billingWeight
     *
     * @param billingweight the value for lg_order.billingWeight
     *
     * @mbggenerated
     */
    public void setBillingweight(Double billingweight) {
        this.billingweight = billingweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.shippingType
     *
     * @return the value of lg_order.shippingType
     *
     * @mbggenerated
     */
    public Integer getShippingtype() {
        return shippingtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.shippingType
     *
     * @param shippingtype the value for lg_order.shippingType
     *
     * @mbggenerated
     */
    public void setShippingtype(Integer shippingtype) {
        this.shippingtype = shippingtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.vehicleType
     *
     * @return the value of lg_order.vehicleType
     *
     * @mbggenerated
     */
    public Integer getVehicletype() {
        return vehicletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.vehicleType
     *
     * @param vehicletype the value for lg_order.vehicleType
     *
     * @mbggenerated
     */
    public void setVehicletype(Integer vehicletype) {
        this.vehicletype = vehicletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.valueGoods
     *
     * @return the value of lg_order.valueGoods
     *
     * @mbggenerated
     */
    public Double getValuegoods() {
        return valuegoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.valueGoods
     *
     * @param valuegoods the value for lg_order.valueGoods
     *
     * @mbggenerated
     */
    public void setValuegoods(Double valuegoods) {
        this.valuegoods = valuegoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.affiliatedCompanyId
     *
     * @return the value of lg_order.affiliatedCompanyId
     *
     * @mbggenerated
     */
    public Integer getAffiliatedcompanyid() {
        return affiliatedcompanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.affiliatedCompanyId
     *
     * @param affiliatedcompanyid the value for lg_order.affiliatedCompanyId
     *
     * @mbggenerated
     */
    public void setAffiliatedcompanyid(Integer affiliatedcompanyid) {
        this.affiliatedcompanyid = affiliatedcompanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.remarks
     *
     * @return the value of lg_order.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.remarks
     *
     * @param remarks the value for lg_order.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.orderFreight
     *
     * @return the value of lg_order.orderFreight
     *
     * @mbggenerated
     */
    public Double getOrderfreight() {
        return orderfreight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.orderFreight
     *
     * @param orderfreight the value for lg_order.orderFreight
     *
     * @mbggenerated
     */
    public void setOrderfreight(Double orderfreight) {
        this.orderfreight = orderfreight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.pickupCharge
     *
     * @return the value of lg_order.pickupCharge
     *
     * @mbggenerated
     */
    public Double getPickupcharge() {
        return pickupcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.pickupCharge
     *
     * @param pickupcharge the value for lg_order.pickupCharge
     *
     * @mbggenerated
     */
    public void setPickupcharge(Double pickupcharge) {
        this.pickupcharge = pickupcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.deliverFee
     *
     * @return the value of lg_order.deliverFee
     *
     * @mbggenerated
     */
    public Double getDeliverfee() {
        return deliverfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.deliverFee
     *
     * @param deliverfee the value for lg_order.deliverFee
     *
     * @mbggenerated
     */
    public void setDeliverfee(Double deliverfee) {
        this.deliverfee = deliverfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.insurancePremium
     *
     * @return the value of lg_order.insurancePremium
     *
     * @mbggenerated
     */
    public Double getInsurancepremium() {
        return insurancepremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.insurancePremium
     *
     * @param insurancepremium the value for lg_order.insurancePremium
     *
     * @mbggenerated
     */
    public void setInsurancepremium(Double insurancepremium) {
        this.insurancepremium = insurancepremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.handlingCharges
     *
     * @return the value of lg_order.handlingCharges
     *
     * @mbggenerated
     */
    public Double getHandlingcharges() {
        return handlingcharges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.handlingCharges
     *
     * @param handlingcharges the value for lg_order.handlingCharges
     *
     * @mbggenerated
     */
    public void setHandlingcharges(Double handlingcharges) {
        this.handlingcharges = handlingcharges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.otherExpenses
     *
     * @return the value of lg_order.otherExpenses
     *
     * @mbggenerated
     */
    public Double getOtherexpenses() {
        return otherexpenses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.otherExpenses
     *
     * @param otherexpenses the value for lg_order.otherExpenses
     *
     * @mbggenerated
     */
    public void setOtherexpenses(Double otherexpenses) {
        this.otherexpenses = otherexpenses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.settlementMethod
     *
     * @return the value of lg_order.settlementMethod
     *
     * @mbggenerated
     */
    public Integer getSettlementmethod() {
        return settlementmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.settlementMethod
     *
     * @param settlementmethod the value for lg_order.settlementMethod
     *
     * @mbggenerated
     */
    public void setSettlementmethod(Integer settlementmethod) {
        this.settlementmethod = settlementmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.collectionAmount
     *
     * @return the value of lg_order.collectionAmount
     *
     * @mbggenerated
     */
    public Double getCollectionamount() {
        return collectionamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.collectionAmount
     *
     * @param collectionamount the value for lg_order.collectionAmount
     *
     * @mbggenerated
     */
    public void setCollectionamount(Double collectionamount) {
        this.collectionamount = collectionamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.advanceCollection
     *
     * @return the value of lg_order.advanceCollection
     *
     * @mbggenerated
     */
    public Double getAdvancecollection() {
        return advancecollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.advanceCollection
     *
     * @param advancecollection the value for lg_order.advanceCollection
     *
     * @mbggenerated
     */
    public void setAdvancecollection(Double advancecollection) {
        this.advancecollection = advancecollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.receivableLiablePerson
     *
     * @return the value of lg_order.receivableLiablePerson
     *
     * @mbggenerated
     */
    public String getReceivableliableperson() {
        return receivableliableperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.receivableLiablePerson
     *
     * @param receivableliableperson the value for lg_order.receivableLiablePerson
     *
     * @mbggenerated
     */
    public void setReceivableliableperson(String receivableliableperson) {
        this.receivableliableperson = receivableliableperson == null ? null : receivableliableperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.receivableCompany
     *
     * @return the value of lg_order.receivableCompany
     *
     * @mbggenerated
     */
    public String getReceivablecompany() {
        return receivablecompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.receivableCompany
     *
     * @param receivablecompany the value for lg_order.receivableCompany
     *
     * @mbggenerated
     */
    public void setReceivablecompany(String receivablecompany) {
        this.receivablecompany = receivablecompany == null ? null : receivablecompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.orderStatus
     *
     * @return the value of lg_order.orderStatus
     *
     * @mbggenerated
     */
    public Integer getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.orderStatus
     *
     * @param orderstatus the value for lg_order.orderStatus
     *
     * @mbggenerated
     */
    public void setOrderstatus(Integer orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_order.orderType
     *
     * @return the value of lg_order.orderType
     *
     * @mbggenerated
     */
    public Integer getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_order.orderType
     *
     * @param ordertype the value for lg_order.orderType
     *
     * @mbggenerated
     */
    public void setOrdertype(Integer ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderid=").append(orderid);
        sb.append(", shipperid=").append(shipperid);
        sb.append(", receivingpartyid=").append(receivingpartyid);
        sb.append(", originatingplace=").append(originatingplace);
        sb.append(", destination=").append(destination);
        sb.append(", deliverytime=").append(deliverytime);
        sb.append(", deliverymode=").append(deliverymode);
        sb.append(", prescriptiorequirement=").append(prescriptiorequirement);
        sb.append(", totalnumber=").append(totalnumber);
        sb.append(", ordervolume=").append(ordervolume);
        sb.append(", totalweight=").append(totalweight);
        sb.append(", billingquantity=").append(billingquantity);
        sb.append(", billingvolume=").append(billingvolume);
        sb.append(", billingweight=").append(billingweight);
        sb.append(", shippingtype=").append(shippingtype);
        sb.append(", vehicletype=").append(vehicletype);
        sb.append(", valuegoods=").append(valuegoods);
        sb.append(", affiliatedcompanyid=").append(affiliatedcompanyid);
        sb.append(", remarks=").append(remarks);
        sb.append(", orderfreight=").append(orderfreight);
        sb.append(", pickupcharge=").append(pickupcharge);
        sb.append(", deliverfee=").append(deliverfee);
        sb.append(", insurancepremium=").append(insurancepremium);
        sb.append(", handlingcharges=").append(handlingcharges);
        sb.append(", otherexpenses=").append(otherexpenses);
        sb.append(", settlementmethod=").append(settlementmethod);
        sb.append(", collectionamount=").append(collectionamount);
        sb.append(", advancecollection=").append(advancecollection);
        sb.append(", receivableliableperson=").append(receivableliableperson);
        sb.append(", receivablecompany=").append(receivablecompany);
        sb.append(", orderstatus=").append(orderstatus);
        sb.append(", ordertype=").append(ordertype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}