package cn.log.pojo;

import java.io.Serializable;

public class LgOrderwaybill implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_orderwaybill.orderWayBillId
     *
     * @mbggenerated
     */
    private Integer orderwaybillid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_orderwaybill.orderId
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_orderwaybill.wayBillId
     *
     * @mbggenerated
     */
    private Integer waybillid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_orderwaybill
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_orderwaybill.orderWayBillId
     *
     * @return the value of lg_orderwaybill.orderWayBillId
     *
     * @mbggenerated
     */
    public Integer getOrderwaybillid() {
        return orderwaybillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_orderwaybill.orderWayBillId
     *
     * @param orderwaybillid the value for lg_orderwaybill.orderWayBillId
     *
     * @mbggenerated
     */
    public void setOrderwaybillid(Integer orderwaybillid) {
        this.orderwaybillid = orderwaybillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_orderwaybill.orderId
     *
     * @return the value of lg_orderwaybill.orderId
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_orderwaybill.orderId
     *
     * @param orderid the value for lg_orderwaybill.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_orderwaybill.wayBillId
     *
     * @return the value of lg_orderwaybill.wayBillId
     *
     * @mbggenerated
     */
    public Integer getWaybillid() {
        return waybillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_orderwaybill.wayBillId
     *
     * @param waybillid the value for lg_orderwaybill.wayBillId
     *
     * @mbggenerated
     */
    public void setWaybillid(Integer waybillid) {
        this.waybillid = waybillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_orderwaybill
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderwaybillid=").append(orderwaybillid);
        sb.append(", orderid=").append(orderid);
        sb.append(", waybillid=").append(waybillid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}