package cn.log.pojo;

import java.io.Serializable;

public class LgOutboundgoods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_outboundgoods.outboundGoodsId
     *
     * @mbggenerated
     */
    private Integer outboundgoodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_outboundgoods.outboundId
     *
     * @mbggenerated
     */
    private Integer outboundid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_outboundgoods.goodsId
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_outboundgoods.outgoingQuantity
     *
     * @mbggenerated
     */
    private Integer outgoingquantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_outboundgoods
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_outboundgoods.outboundGoodsId
     *
     * @return the value of lg_outboundgoods.outboundGoodsId
     *
     * @mbggenerated
     */
    public Integer getOutboundgoodsid() {
        return outboundgoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_outboundgoods.outboundGoodsId
     *
     * @param outboundgoodsid the value for lg_outboundgoods.outboundGoodsId
     *
     * @mbggenerated
     */
    public void setOutboundgoodsid(Integer outboundgoodsid) {
        this.outboundgoodsid = outboundgoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_outboundgoods.outboundId
     *
     * @return the value of lg_outboundgoods.outboundId
     *
     * @mbggenerated
     */
    public Integer getOutboundid() {
        return outboundid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_outboundgoods.outboundId
     *
     * @param outboundid the value for lg_outboundgoods.outboundId
     *
     * @mbggenerated
     */
    public void setOutboundid(Integer outboundid) {
        this.outboundid = outboundid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_outboundgoods.goodsId
     *
     * @return the value of lg_outboundgoods.goodsId
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_outboundgoods.goodsId
     *
     * @param goodsid the value for lg_outboundgoods.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_outboundgoods.outgoingQuantity
     *
     * @return the value of lg_outboundgoods.outgoingQuantity
     *
     * @mbggenerated
     */
    public Integer getOutgoingquantity() {
        return outgoingquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_outboundgoods.outgoingQuantity
     *
     * @param outgoingquantity the value for lg_outboundgoods.outgoingQuantity
     *
     * @mbggenerated
     */
    public void setOutgoingquantity(Integer outgoingquantity) {
        this.outgoingquantity = outgoingquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_outboundgoods
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", outboundgoodsid=").append(outboundgoodsid);
        sb.append(", outboundid=").append(outboundid);
        sb.append(", goodsid=").append(goodsid);
        sb.append(", outgoingquantity=").append(outgoingquantity);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}