package cn.log.pojo;

import java.io.Serializable;
import java.util.Date;

public class LgOutbound implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_outbound.outboundId
     *
     * @mbggenerated
     */
    private Integer outboundid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_outbound.outgoingNumber
     *
     * @mbggenerated
     */
    private Integer outgoingnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_outbound.outgoingTime
     *
     * @mbggenerated
     */
    private Date outgoingtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_outbound.cargoDamaged
     *
     * @mbggenerated
     */
    private Integer cargodamaged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_outbound.goodsDamageId
     *
     * @mbggenerated
     */
    private Integer goodsdamageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_outbound.storekeeperId
     *
     * @mbggenerated
     */
    private Integer storekeeperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_outbound.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_outbound.warehouseId
     *
     * @mbggenerated
     */
    private Integer warehouseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_outbound.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_outbound.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_outbound
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_outbound.outboundId
     *
     * @return the value of lg_outbound.outboundId
     *
     * @mbggenerated
     */
    public Integer getOutboundid() {
        return outboundid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_outbound.outboundId
     *
     * @param outboundid the value for lg_outbound.outboundId
     *
     * @mbggenerated
     */
    public void setOutboundid(Integer outboundid) {
        this.outboundid = outboundid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_outbound.outgoingNumber
     *
     * @return the value of lg_outbound.outgoingNumber
     *
     * @mbggenerated
     */
    public Integer getOutgoingnumber() {
        return outgoingnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_outbound.outgoingNumber
     *
     * @param outgoingnumber the value for lg_outbound.outgoingNumber
     *
     * @mbggenerated
     */
    public void setOutgoingnumber(Integer outgoingnumber) {
        this.outgoingnumber = outgoingnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_outbound.outgoingTime
     *
     * @return the value of lg_outbound.outgoingTime
     *
     * @mbggenerated
     */
    public Date getOutgoingtime() {
        return outgoingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_outbound.outgoingTime
     *
     * @param outgoingtime the value for lg_outbound.outgoingTime
     *
     * @mbggenerated
     */
    public void setOutgoingtime(Date outgoingtime) {
        this.outgoingtime = outgoingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_outbound.cargoDamaged
     *
     * @return the value of lg_outbound.cargoDamaged
     *
     * @mbggenerated
     */
    public Integer getCargodamaged() {
        return cargodamaged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_outbound.cargoDamaged
     *
     * @param cargodamaged the value for lg_outbound.cargoDamaged
     *
     * @mbggenerated
     */
    public void setCargodamaged(Integer cargodamaged) {
        this.cargodamaged = cargodamaged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_outbound.goodsDamageId
     *
     * @return the value of lg_outbound.goodsDamageId
     *
     * @mbggenerated
     */
    public Integer getGoodsdamageid() {
        return goodsdamageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_outbound.goodsDamageId
     *
     * @param goodsdamageid the value for lg_outbound.goodsDamageId
     *
     * @mbggenerated
     */
    public void setGoodsdamageid(Integer goodsdamageid) {
        this.goodsdamageid = goodsdamageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_outbound.storekeeperId
     *
     * @return the value of lg_outbound.storekeeperId
     *
     * @mbggenerated
     */
    public Integer getStorekeeperid() {
        return storekeeperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_outbound.storekeeperId
     *
     * @param storekeeperid the value for lg_outbound.storekeeperId
     *
     * @mbggenerated
     */
    public void setStorekeeperid(Integer storekeeperid) {
        this.storekeeperid = storekeeperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_outbound.remarks
     *
     * @return the value of lg_outbound.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_outbound.remarks
     *
     * @param remarks the value for lg_outbound.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_outbound.warehouseId
     *
     * @return the value of lg_outbound.warehouseId
     *
     * @mbggenerated
     */
    public Integer getWarehouseid() {
        return warehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_outbound.warehouseId
     *
     * @param warehouseid the value for lg_outbound.warehouseId
     *
     * @mbggenerated
     */
    public void setWarehouseid(Integer warehouseid) {
        this.warehouseid = warehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_outbound.remarks1
     *
     * @return the value of lg_outbound.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_outbound.remarks1
     *
     * @param remarks1 the value for lg_outbound.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_outbound.remarks2
     *
     * @return the value of lg_outbound.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_outbound.remarks2
     *
     * @param remarks2 the value for lg_outbound.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_outbound
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", outboundid=").append(outboundid);
        sb.append(", outgoingnumber=").append(outgoingnumber);
        sb.append(", outgoingtime=").append(outgoingtime);
        sb.append(", cargodamaged=").append(cargodamaged);
        sb.append(", goodsdamageid=").append(goodsdamageid);
        sb.append(", storekeeperid=").append(storekeeperid);
        sb.append(", remarks=").append(remarks);
        sb.append(", warehouseid=").append(warehouseid);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}