package cn.log.pojo;

import java.io.Serializable;
import java.util.Date;

public class LgPerms implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_perms.permsId
     *
     * @mbggenerated
     */
    private Integer permsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_perms.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_perms.permsName
     *
     * @mbggenerated
     */
    private String permsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_perms.perms
     *
     * @mbggenerated
     */
    private String perms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_perms.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_perms.createBy
     *
     * @mbggenerated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_perms.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_perms.updateBy
     *
     * @mbggenerated
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_perms.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_perms.remark1
     *
     * @mbggenerated
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_perms.remark2
     *
     * @mbggenerated
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_perms
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_perms.permsId
     *
     * @return the value of lg_perms.permsId
     *
     * @mbggenerated
     */
    public Integer getPermsid() {
        return permsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_perms.permsId
     *
     * @param permsid the value for lg_perms.permsId
     *
     * @mbggenerated
     */
    public void setPermsid(Integer permsid) {
        this.permsid = permsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_perms.url
     *
     * @return the value of lg_perms.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_perms.url
     *
     * @param url the value for lg_perms.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_perms.permsName
     *
     * @return the value of lg_perms.permsName
     *
     * @mbggenerated
     */
    public String getPermsname() {
        return permsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_perms.permsName
     *
     * @param permsname the value for lg_perms.permsName
     *
     * @mbggenerated
     */
    public void setPermsname(String permsname) {
        this.permsname = permsname == null ? null : permsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_perms.perms
     *
     * @return the value of lg_perms.perms
     *
     * @mbggenerated
     */
    public String getPerms() {
        return perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_perms.perms
     *
     * @param perms the value for lg_perms.perms
     *
     * @mbggenerated
     */
    public void setPerms(String perms) {
        this.perms = perms == null ? null : perms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_perms.desc
     *
     * @return the value of lg_perms.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_perms.desc
     *
     * @param desc the value for lg_perms.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_perms.createBy
     *
     * @return the value of lg_perms.createBy
     *
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_perms.createBy
     *
     * @param createby the value for lg_perms.createBy
     *
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_perms.createTime
     *
     * @return the value of lg_perms.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_perms.createTime
     *
     * @param createtime the value for lg_perms.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_perms.updateBy
     *
     * @return the value of lg_perms.updateBy
     *
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_perms.updateBy
     *
     * @param updateby the value for lg_perms.updateBy
     *
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby == null ? null : updateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_perms.updateTime
     *
     * @return the value of lg_perms.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_perms.updateTime
     *
     * @param updatetime the value for lg_perms.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_perms.remark1
     *
     * @return the value of lg_perms.remark1
     *
     * @mbggenerated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_perms.remark1
     *
     * @param remark1 the value for lg_perms.remark1
     *
     * @mbggenerated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_perms.remark2
     *
     * @return the value of lg_perms.remark2
     *
     * @mbggenerated
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_perms.remark2
     *
     * @param remark2 the value for lg_perms.remark2
     *
     * @mbggenerated
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_perms
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", permsid=").append(permsid);
        sb.append(", url=").append(url);
        sb.append(", permsname=").append(permsname);
        sb.append(", perms=").append(perms);
        sb.append(", desc=").append(desc);
        sb.append(", createby=").append(createby);
        sb.append(", createtime=").append(createtime);
        sb.append(", updateby=").append(updateby);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", remark1=").append(remark1);
        sb.append(", remark2=").append(remark2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}