package cn.log.pojo;

import java.io.Serializable;

public class LgReceivingparty implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_receivingparty.receivingPartyId
     *
     * @mbggenerated
     */
    private Integer receivingpartyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_receivingparty.receivingName
     *
     * @mbggenerated
     */
    private String receivingname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_receivingparty.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_receivingparty.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_receivingparty.prescriptionRequirement
     *
     * @mbggenerated
     */
    private String prescriptionrequirement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_receivingparty.receiptRequest
     *
     * @mbggenerated
     */
    private String receiptrequest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_receivingparty.returnPeriod
     *
     * @mbggenerated
     */
    private String returnperiod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_receivingparty.cooperationStatus
     *
     * @mbggenerated
     */
    private Integer cooperationstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_receivingparty.minimumGrossRate
     *
     * @mbggenerated
     */
    private Double minimumgrossrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_receivingparty.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_receivingparty.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_receivingparty.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_receivingparty
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_receivingparty.receivingPartyId
     *
     * @return the value of lg_receivingparty.receivingPartyId
     *
     * @mbggenerated
     */
    public Integer getReceivingpartyid() {
        return receivingpartyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_receivingparty.receivingPartyId
     *
     * @param receivingpartyid the value for lg_receivingparty.receivingPartyId
     *
     * @mbggenerated
     */
    public void setReceivingpartyid(Integer receivingpartyid) {
        this.receivingpartyid = receivingpartyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_receivingparty.receivingName
     *
     * @return the value of lg_receivingparty.receivingName
     *
     * @mbggenerated
     */
    public String getReceivingname() {
        return receivingname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_receivingparty.receivingName
     *
     * @param receivingname the value for lg_receivingparty.receivingName
     *
     * @mbggenerated
     */
    public void setReceivingname(String receivingname) {
        this.receivingname = receivingname == null ? null : receivingname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_receivingparty.phone
     *
     * @return the value of lg_receivingparty.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_receivingparty.phone
     *
     * @param phone the value for lg_receivingparty.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_receivingparty.address
     *
     * @return the value of lg_receivingparty.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_receivingparty.address
     *
     * @param address the value for lg_receivingparty.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_receivingparty.prescriptionRequirement
     *
     * @return the value of lg_receivingparty.prescriptionRequirement
     *
     * @mbggenerated
     */
    public String getPrescriptionrequirement() {
        return prescriptionrequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_receivingparty.prescriptionRequirement
     *
     * @param prescriptionrequirement the value for lg_receivingparty.prescriptionRequirement
     *
     * @mbggenerated
     */
    public void setPrescriptionrequirement(String prescriptionrequirement) {
        this.prescriptionrequirement = prescriptionrequirement == null ? null : prescriptionrequirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_receivingparty.receiptRequest
     *
     * @return the value of lg_receivingparty.receiptRequest
     *
     * @mbggenerated
     */
    public String getReceiptrequest() {
        return receiptrequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_receivingparty.receiptRequest
     *
     * @param receiptrequest the value for lg_receivingparty.receiptRequest
     *
     * @mbggenerated
     */
    public void setReceiptrequest(String receiptrequest) {
        this.receiptrequest = receiptrequest == null ? null : receiptrequest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_receivingparty.returnPeriod
     *
     * @return the value of lg_receivingparty.returnPeriod
     *
     * @mbggenerated
     */
    public String getReturnperiod() {
        return returnperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_receivingparty.returnPeriod
     *
     * @param returnperiod the value for lg_receivingparty.returnPeriod
     *
     * @mbggenerated
     */
    public void setReturnperiod(String returnperiod) {
        this.returnperiod = returnperiod == null ? null : returnperiod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_receivingparty.cooperationStatus
     *
     * @return the value of lg_receivingparty.cooperationStatus
     *
     * @mbggenerated
     */
    public Integer getCooperationstatus() {
        return cooperationstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_receivingparty.cooperationStatus
     *
     * @param cooperationstatus the value for lg_receivingparty.cooperationStatus
     *
     * @mbggenerated
     */
    public void setCooperationstatus(Integer cooperationstatus) {
        this.cooperationstatus = cooperationstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_receivingparty.minimumGrossRate
     *
     * @return the value of lg_receivingparty.minimumGrossRate
     *
     * @mbggenerated
     */
    public Double getMinimumgrossrate() {
        return minimumgrossrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_receivingparty.minimumGrossRate
     *
     * @param minimumgrossrate the value for lg_receivingparty.minimumGrossRate
     *
     * @mbggenerated
     */
    public void setMinimumgrossrate(Double minimumgrossrate) {
        this.minimumgrossrate = minimumgrossrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_receivingparty.remarks
     *
     * @return the value of lg_receivingparty.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_receivingparty.remarks
     *
     * @param remarks the value for lg_receivingparty.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_receivingparty.remarks1
     *
     * @return the value of lg_receivingparty.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_receivingparty.remarks1
     *
     * @param remarks1 the value for lg_receivingparty.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_receivingparty.remarks2
     *
     * @return the value of lg_receivingparty.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_receivingparty.remarks2
     *
     * @param remarks2 the value for lg_receivingparty.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_receivingparty
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", receivingpartyid=").append(receivingpartyid);
        sb.append(", receivingname=").append(receivingname);
        sb.append(", phone=").append(phone);
        sb.append(", address=").append(address);
        sb.append(", prescriptionrequirement=").append(prescriptionrequirement);
        sb.append(", receiptrequest=").append(receiptrequest);
        sb.append(", returnperiod=").append(returnperiod);
        sb.append(", cooperationstatus=").append(cooperationstatus);
        sb.append(", minimumgrossrate=").append(minimumgrossrate);
        sb.append(", remarks=").append(remarks);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}