package cn.log.pojo;

import java.io.Serializable;

public class LgRolePerm implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_role_perm.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_role_perm.roleId
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_role_perm.permsId
     *
     * @mbggenerated
     */
    private Integer permsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_role_perm
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_role_perm.id
     *
     * @return the value of lg_role_perm.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_role_perm.id
     *
     * @param id the value for lg_role_perm.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_role_perm.roleId
     *
     * @return the value of lg_role_perm.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_role_perm.roleId
     *
     * @param roleid the value for lg_role_perm.roleId
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_role_perm.permsId
     *
     * @return the value of lg_role_perm.permsId
     *
     * @mbggenerated
     */
    public Integer getPermsid() {
        return permsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_role_perm.permsId
     *
     * @param permsid the value for lg_role_perm.permsId
     *
     * @mbggenerated
     */
    public void setPermsid(Integer permsid) {
        this.permsid = permsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_role_perm
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleid=").append(roleid);
        sb.append(", permsid=").append(permsid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}