package cn.log.pojo;

import java.io.Serializable;
import java.util.Date;

public class LgShipper implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.shipperId
     *
     * @mbggenerated
     */
    private Integer shipperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.shipperName
     *
     * @mbggenerated
     */
    private String shippername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.idCard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.bankTransferAccount
     *
     * @mbggenerated
     */
    private String banktransferaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.bankDeposit
     *
     * @mbggenerated
     */
    private String bankdeposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.contractServiceContent
     *
     * @mbggenerated
     */
    private String contractservicecontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.contractNumber
     *
     * @mbggenerated
     */
    private String contractnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.contractStartingDate
     *
     * @mbggenerated
     */
    private Date contractstartingdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.contractEndDate
     *
     * @mbggenerated
     */
    private Date contractenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.loadingContact
     *
     * @mbggenerated
     */
    private String loadingcontact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.loadingAddress
     *
     * @mbggenerated
     */
    private String loadingaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.loadingPhone
     *
     * @mbggenerated
     */
    private String loadingphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.logisticsRates
     *
     * @mbggenerated
     */
    private Double logisticsrates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.shipperType
     *
     * @mbggenerated
     */
    private Integer shippertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.contractStatus
     *
     * @mbggenerated
     */
    private Integer contractstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.contractSettlementDate
     *
     * @mbggenerated
     */
    private Date contractsettlementdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.receivableLiablePerson
     *
     * @mbggenerated
     */
    private String receivableliableperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.salesMan
     *
     * @mbggenerated
     */
    private String salesman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_shipper.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_shipper
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.shipperId
     *
     * @return the value of lg_shipper.shipperId
     *
     * @mbggenerated
     */
    public Integer getShipperid() {
        return shipperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.shipperId
     *
     * @param shipperid the value for lg_shipper.shipperId
     *
     * @mbggenerated
     */
    public void setShipperid(Integer shipperid) {
        this.shipperid = shipperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.shipperName
     *
     * @return the value of lg_shipper.shipperName
     *
     * @mbggenerated
     */
    public String getShippername() {
        return shippername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.shipperName
     *
     * @param shippername the value for lg_shipper.shipperName
     *
     * @mbggenerated
     */
    public void setShippername(String shippername) {
        this.shippername = shippername == null ? null : shippername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.phone
     *
     * @return the value of lg_shipper.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.phone
     *
     * @param phone the value for lg_shipper.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.address
     *
     * @return the value of lg_shipper.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.address
     *
     * @param address the value for lg_shipper.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.gender
     *
     * @return the value of lg_shipper.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.gender
     *
     * @param gender the value for lg_shipper.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.idCard
     *
     * @return the value of lg_shipper.idCard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.idCard
     *
     * @param idcard the value for lg_shipper.idCard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.bankTransferAccount
     *
     * @return the value of lg_shipper.bankTransferAccount
     *
     * @mbggenerated
     */
    public String getBanktransferaccount() {
        return banktransferaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.bankTransferAccount
     *
     * @param banktransferaccount the value for lg_shipper.bankTransferAccount
     *
     * @mbggenerated
     */
    public void setBanktransferaccount(String banktransferaccount) {
        this.banktransferaccount = banktransferaccount == null ? null : banktransferaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.bankDeposit
     *
     * @return the value of lg_shipper.bankDeposit
     *
     * @mbggenerated
     */
    public String getBankdeposit() {
        return bankdeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.bankDeposit
     *
     * @param bankdeposit the value for lg_shipper.bankDeposit
     *
     * @mbggenerated
     */
    public void setBankdeposit(String bankdeposit) {
        this.bankdeposit = bankdeposit == null ? null : bankdeposit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.contractServiceContent
     *
     * @return the value of lg_shipper.contractServiceContent
     *
     * @mbggenerated
     */
    public String getContractservicecontent() {
        return contractservicecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.contractServiceContent
     *
     * @param contractservicecontent the value for lg_shipper.contractServiceContent
     *
     * @mbggenerated
     */
    public void setContractservicecontent(String contractservicecontent) {
        this.contractservicecontent = contractservicecontent == null ? null : contractservicecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.contractNumber
     *
     * @return the value of lg_shipper.contractNumber
     *
     * @mbggenerated
     */
    public String getContractnumber() {
        return contractnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.contractNumber
     *
     * @param contractnumber the value for lg_shipper.contractNumber
     *
     * @mbggenerated
     */
    public void setContractnumber(String contractnumber) {
        this.contractnumber = contractnumber == null ? null : contractnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.contractStartingDate
     *
     * @return the value of lg_shipper.contractStartingDate
     *
     * @mbggenerated
     */
    public Date getContractstartingdate() {
        return contractstartingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.contractStartingDate
     *
     * @param contractstartingdate the value for lg_shipper.contractStartingDate
     *
     * @mbggenerated
     */
    public void setContractstartingdate(Date contractstartingdate) {
        this.contractstartingdate = contractstartingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.contractEndDate
     *
     * @return the value of lg_shipper.contractEndDate
     *
     * @mbggenerated
     */
    public Date getContractenddate() {
        return contractenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.contractEndDate
     *
     * @param contractenddate the value for lg_shipper.contractEndDate
     *
     * @mbggenerated
     */
    public void setContractenddate(Date contractenddate) {
        this.contractenddate = contractenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.email
     *
     * @return the value of lg_shipper.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.email
     *
     * @param email the value for lg_shipper.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.loadingContact
     *
     * @return the value of lg_shipper.loadingContact
     *
     * @mbggenerated
     */
    public String getLoadingcontact() {
        return loadingcontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.loadingContact
     *
     * @param loadingcontact the value for lg_shipper.loadingContact
     *
     * @mbggenerated
     */
    public void setLoadingcontact(String loadingcontact) {
        this.loadingcontact = loadingcontact == null ? null : loadingcontact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.loadingAddress
     *
     * @return the value of lg_shipper.loadingAddress
     *
     * @mbggenerated
     */
    public String getLoadingaddress() {
        return loadingaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.loadingAddress
     *
     * @param loadingaddress the value for lg_shipper.loadingAddress
     *
     * @mbggenerated
     */
    public void setLoadingaddress(String loadingaddress) {
        this.loadingaddress = loadingaddress == null ? null : loadingaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.loadingPhone
     *
     * @return the value of lg_shipper.loadingPhone
     *
     * @mbggenerated
     */
    public String getLoadingphone() {
        return loadingphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.loadingPhone
     *
     * @param loadingphone the value for lg_shipper.loadingPhone
     *
     * @mbggenerated
     */
    public void setLoadingphone(String loadingphone) {
        this.loadingphone = loadingphone == null ? null : loadingphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.logisticsRates
     *
     * @return the value of lg_shipper.logisticsRates
     *
     * @mbggenerated
     */
    public Double getLogisticsrates() {
        return logisticsrates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.logisticsRates
     *
     * @param logisticsrates the value for lg_shipper.logisticsRates
     *
     * @mbggenerated
     */
    public void setLogisticsrates(Double logisticsrates) {
        this.logisticsrates = logisticsrates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.shipperType
     *
     * @return the value of lg_shipper.shipperType
     *
     * @mbggenerated
     */
    public Integer getShippertype() {
        return shippertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.shipperType
     *
     * @param shippertype the value for lg_shipper.shipperType
     *
     * @mbggenerated
     */
    public void setShippertype(Integer shippertype) {
        this.shippertype = shippertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.contractStatus
     *
     * @return the value of lg_shipper.contractStatus
     *
     * @mbggenerated
     */
    public Integer getContractstatus() {
        return contractstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.contractStatus
     *
     * @param contractstatus the value for lg_shipper.contractStatus
     *
     * @mbggenerated
     */
    public void setContractstatus(Integer contractstatus) {
        this.contractstatus = contractstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.contractSettlementDate
     *
     * @return the value of lg_shipper.contractSettlementDate
     *
     * @mbggenerated
     */
    public Date getContractsettlementdate() {
        return contractsettlementdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.contractSettlementDate
     *
     * @param contractsettlementdate the value for lg_shipper.contractSettlementDate
     *
     * @mbggenerated
     */
    public void setContractsettlementdate(Date contractsettlementdate) {
        this.contractsettlementdate = contractsettlementdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.receivableLiablePerson
     *
     * @return the value of lg_shipper.receivableLiablePerson
     *
     * @mbggenerated
     */
    public String getReceivableliableperson() {
        return receivableliableperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.receivableLiablePerson
     *
     * @param receivableliableperson the value for lg_shipper.receivableLiablePerson
     *
     * @mbggenerated
     */
    public void setReceivableliableperson(String receivableliableperson) {
        this.receivableliableperson = receivableliableperson == null ? null : receivableliableperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.salesMan
     *
     * @return the value of lg_shipper.salesMan
     *
     * @mbggenerated
     */
    public String getSalesman() {
        return salesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.salesMan
     *
     * @param salesman the value for lg_shipper.salesMan
     *
     * @mbggenerated
     */
    public void setSalesman(String salesman) {
        this.salesman = salesman == null ? null : salesman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.remarks
     *
     * @return the value of lg_shipper.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.remarks
     *
     * @param remarks the value for lg_shipper.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.remarks1
     *
     * @return the value of lg_shipper.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.remarks1
     *
     * @param remarks1 the value for lg_shipper.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_shipper.remarks2
     *
     * @return the value of lg_shipper.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_shipper.remarks2
     *
     * @param remarks2 the value for lg_shipper.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_shipper
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shipperid=").append(shipperid);
        sb.append(", shippername=").append(shippername);
        sb.append(", phone=").append(phone);
        sb.append(", address=").append(address);
        sb.append(", gender=").append(gender);
        sb.append(", idcard=").append(idcard);
        sb.append(", banktransferaccount=").append(banktransferaccount);
        sb.append(", bankdeposit=").append(bankdeposit);
        sb.append(", contractservicecontent=").append(contractservicecontent);
        sb.append(", contractnumber=").append(contractnumber);
        sb.append(", contractstartingdate=").append(contractstartingdate);
        sb.append(", contractenddate=").append(contractenddate);
        sb.append(", email=").append(email);
        sb.append(", loadingcontact=").append(loadingcontact);
        sb.append(", loadingaddress=").append(loadingaddress);
        sb.append(", loadingphone=").append(loadingphone);
        sb.append(", logisticsrates=").append(logisticsrates);
        sb.append(", shippertype=").append(shippertype);
        sb.append(", contractstatus=").append(contractstatus);
        sb.append(", contractsettlementdate=").append(contractsettlementdate);
        sb.append(", receivableliableperson=").append(receivableliableperson);
        sb.append(", salesman=").append(salesman);
        sb.append(", remarks=").append(remarks);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}