package cn.log.pojo;

import java.io.Serializable;
import java.util.Date;

public class LgVehicleinspection implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicleinspection.vehicleOperationId
     *
     * @mbggenerated
     */
    private Integer vehicleoperationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicleinspection.verificationItems
     *
     * @mbggenerated
     */
    private String verificationitems;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicleinspection.verificationTime
     *
     * @mbggenerated
     */
    private Date verificationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicleinspection.nexttrialTime
     *
     * @mbggenerated
     */
    private Date nexttrialtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicleinspection.nextAuditStatus
     *
     * @mbggenerated
     */
    private Integer nextauditstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicleinspection.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicleinspection.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_vehicleinspection
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicleinspection.vehicleOperationId
     *
     * @return the value of lg_vehicleinspection.vehicleOperationId
     *
     * @mbggenerated
     */
    public Integer getVehicleoperationid() {
        return vehicleoperationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicleinspection.vehicleOperationId
     *
     * @param vehicleoperationid the value for lg_vehicleinspection.vehicleOperationId
     *
     * @mbggenerated
     */
    public void setVehicleoperationid(Integer vehicleoperationid) {
        this.vehicleoperationid = vehicleoperationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicleinspection.verificationItems
     *
     * @return the value of lg_vehicleinspection.verificationItems
     *
     * @mbggenerated
     */
    public String getVerificationitems() {
        return verificationitems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicleinspection.verificationItems
     *
     * @param verificationitems the value for lg_vehicleinspection.verificationItems
     *
     * @mbggenerated
     */
    public void setVerificationitems(String verificationitems) {
        this.verificationitems = verificationitems == null ? null : verificationitems.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicleinspection.verificationTime
     *
     * @return the value of lg_vehicleinspection.verificationTime
     *
     * @mbggenerated
     */
    public Date getVerificationtime() {
        return verificationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicleinspection.verificationTime
     *
     * @param verificationtime the value for lg_vehicleinspection.verificationTime
     *
     * @mbggenerated
     */
    public void setVerificationtime(Date verificationtime) {
        this.verificationtime = verificationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicleinspection.nexttrialTime
     *
     * @return the value of lg_vehicleinspection.nexttrialTime
     *
     * @mbggenerated
     */
    public Date getNexttrialtime() {
        return nexttrialtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicleinspection.nexttrialTime
     *
     * @param nexttrialtime the value for lg_vehicleinspection.nexttrialTime
     *
     * @mbggenerated
     */
    public void setNexttrialtime(Date nexttrialtime) {
        this.nexttrialtime = nexttrialtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicleinspection.nextAuditStatus
     *
     * @return the value of lg_vehicleinspection.nextAuditStatus
     *
     * @mbggenerated
     */
    public Integer getNextauditstatus() {
        return nextauditstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicleinspection.nextAuditStatus
     *
     * @param nextauditstatus the value for lg_vehicleinspection.nextAuditStatus
     *
     * @mbggenerated
     */
    public void setNextauditstatus(Integer nextauditstatus) {
        this.nextauditstatus = nextauditstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicleinspection.remarks1
     *
     * @return the value of lg_vehicleinspection.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicleinspection.remarks1
     *
     * @param remarks1 the value for lg_vehicleinspection.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicleinspection.remarks2
     *
     * @return the value of lg_vehicleinspection.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicleinspection.remarks2
     *
     * @param remarks2 the value for lg_vehicleinspection.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleinspection
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vehicleoperationid=").append(vehicleoperationid);
        sb.append(", verificationitems=").append(verificationitems);
        sb.append(", verificationtime=").append(verificationtime);
        sb.append(", nexttrialtime=").append(nexttrialtime);
        sb.append(", nextauditstatus=").append(nextauditstatus);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}