package cn.log.pojo;

import java.io.Serializable;
import java.util.Date;

public class LgVehiclemaintenance implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.vehicleMaintenanceId
     *
     * @mbggenerated
     */
    private Integer vehiclemaintenanceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.vehicleOperationId
     *
     * @mbggenerated
     */
    private Integer vehicleoperationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.mileage
     *
     * @mbggenerated
     */
    private Double mileage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.enterTime
     *
     * @mbggenerated
     */
    private Date entertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.factoryTime
     *
     * @mbggenerated
     */
    private Date factorytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.repairShop
     *
     * @mbggenerated
     */
    private String repairshop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.maintenanceLocation
     *
     * @mbggenerated
     */
    private String maintenancelocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.songCarRen
     *
     * @mbggenerated
     */
    private String songcarren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.hourCost
     *
     * @mbggenerated
     */
    private Double hourcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.materialCost
     *
     * @mbggenerated
     */
    private Double materialcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.aggregateCost
     *
     * @mbggenerated
     */
    private Double aggregatecost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.majorrePlacementParts
     *
     * @mbggenerated
     */
    private String majorreplacementparts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.damage
     *
     * @mbggenerated
     */
    private String damage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.faultDescription
     *
     * @mbggenerated
     */
    private String faultdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.repairDetails
     *
     * @mbggenerated
     */
    private String repairdetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclemaintenance.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_vehiclemaintenance
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.vehicleMaintenanceId
     *
     * @return the value of lg_vehiclemaintenance.vehicleMaintenanceId
     *
     * @mbggenerated
     */
    public Integer getVehiclemaintenanceid() {
        return vehiclemaintenanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.vehicleMaintenanceId
     *
     * @param vehiclemaintenanceid the value for lg_vehiclemaintenance.vehicleMaintenanceId
     *
     * @mbggenerated
     */
    public void setVehiclemaintenanceid(Integer vehiclemaintenanceid) {
        this.vehiclemaintenanceid = vehiclemaintenanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.vehicleOperationId
     *
     * @return the value of lg_vehiclemaintenance.vehicleOperationId
     *
     * @mbggenerated
     */
    public Integer getVehicleoperationid() {
        return vehicleoperationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.vehicleOperationId
     *
     * @param vehicleoperationid the value for lg_vehiclemaintenance.vehicleOperationId
     *
     * @mbggenerated
     */
    public void setVehicleoperationid(Integer vehicleoperationid) {
        this.vehicleoperationid = vehicleoperationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.mileage
     *
     * @return the value of lg_vehiclemaintenance.mileage
     *
     * @mbggenerated
     */
    public Double getMileage() {
        return mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.mileage
     *
     * @param mileage the value for lg_vehiclemaintenance.mileage
     *
     * @mbggenerated
     */
    public void setMileage(Double mileage) {
        this.mileage = mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.enterTime
     *
     * @return the value of lg_vehiclemaintenance.enterTime
     *
     * @mbggenerated
     */
    public Date getEntertime() {
        return entertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.enterTime
     *
     * @param entertime the value for lg_vehiclemaintenance.enterTime
     *
     * @mbggenerated
     */
    public void setEntertime(Date entertime) {
        this.entertime = entertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.factoryTime
     *
     * @return the value of lg_vehiclemaintenance.factoryTime
     *
     * @mbggenerated
     */
    public Date getFactorytime() {
        return factorytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.factoryTime
     *
     * @param factorytime the value for lg_vehiclemaintenance.factoryTime
     *
     * @mbggenerated
     */
    public void setFactorytime(Date factorytime) {
        this.factorytime = factorytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.repairShop
     *
     * @return the value of lg_vehiclemaintenance.repairShop
     *
     * @mbggenerated
     */
    public String getRepairshop() {
        return repairshop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.repairShop
     *
     * @param repairshop the value for lg_vehiclemaintenance.repairShop
     *
     * @mbggenerated
     */
    public void setRepairshop(String repairshop) {
        this.repairshop = repairshop == null ? null : repairshop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.maintenanceLocation
     *
     * @return the value of lg_vehiclemaintenance.maintenanceLocation
     *
     * @mbggenerated
     */
    public String getMaintenancelocation() {
        return maintenancelocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.maintenanceLocation
     *
     * @param maintenancelocation the value for lg_vehiclemaintenance.maintenanceLocation
     *
     * @mbggenerated
     */
    public void setMaintenancelocation(String maintenancelocation) {
        this.maintenancelocation = maintenancelocation == null ? null : maintenancelocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.songCarRen
     *
     * @return the value of lg_vehiclemaintenance.songCarRen
     *
     * @mbggenerated
     */
    public String getSongcarren() {
        return songcarren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.songCarRen
     *
     * @param songcarren the value for lg_vehiclemaintenance.songCarRen
     *
     * @mbggenerated
     */
    public void setSongcarren(String songcarren) {
        this.songcarren = songcarren == null ? null : songcarren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.hourCost
     *
     * @return the value of lg_vehiclemaintenance.hourCost
     *
     * @mbggenerated
     */
    public Double getHourcost() {
        return hourcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.hourCost
     *
     * @param hourcost the value for lg_vehiclemaintenance.hourCost
     *
     * @mbggenerated
     */
    public void setHourcost(Double hourcost) {
        this.hourcost = hourcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.materialCost
     *
     * @return the value of lg_vehiclemaintenance.materialCost
     *
     * @mbggenerated
     */
    public Double getMaterialcost() {
        return materialcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.materialCost
     *
     * @param materialcost the value for lg_vehiclemaintenance.materialCost
     *
     * @mbggenerated
     */
    public void setMaterialcost(Double materialcost) {
        this.materialcost = materialcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.aggregateCost
     *
     * @return the value of lg_vehiclemaintenance.aggregateCost
     *
     * @mbggenerated
     */
    public Double getAggregatecost() {
        return aggregatecost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.aggregateCost
     *
     * @param aggregatecost the value for lg_vehiclemaintenance.aggregateCost
     *
     * @mbggenerated
     */
    public void setAggregatecost(Double aggregatecost) {
        this.aggregatecost = aggregatecost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.majorrePlacementParts
     *
     * @return the value of lg_vehiclemaintenance.majorrePlacementParts
     *
     * @mbggenerated
     */
    public String getMajorreplacementparts() {
        return majorreplacementparts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.majorrePlacementParts
     *
     * @param majorreplacementparts the value for lg_vehiclemaintenance.majorrePlacementParts
     *
     * @mbggenerated
     */
    public void setMajorreplacementparts(String majorreplacementparts) {
        this.majorreplacementparts = majorreplacementparts == null ? null : majorreplacementparts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.damage
     *
     * @return the value of lg_vehiclemaintenance.damage
     *
     * @mbggenerated
     */
    public String getDamage() {
        return damage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.damage
     *
     * @param damage the value for lg_vehiclemaintenance.damage
     *
     * @mbggenerated
     */
    public void setDamage(String damage) {
        this.damage = damage == null ? null : damage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.faultDescription
     *
     * @return the value of lg_vehiclemaintenance.faultDescription
     *
     * @mbggenerated
     */
    public String getFaultdescription() {
        return faultdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.faultDescription
     *
     * @param faultdescription the value for lg_vehiclemaintenance.faultDescription
     *
     * @mbggenerated
     */
    public void setFaultdescription(String faultdescription) {
        this.faultdescription = faultdescription == null ? null : faultdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.repairDetails
     *
     * @return the value of lg_vehiclemaintenance.repairDetails
     *
     * @mbggenerated
     */
    public String getRepairdetails() {
        return repairdetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.repairDetails
     *
     * @param repairdetails the value for lg_vehiclemaintenance.repairDetails
     *
     * @mbggenerated
     */
    public void setRepairdetails(String repairdetails) {
        this.repairdetails = repairdetails == null ? null : repairdetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.remarks1
     *
     * @return the value of lg_vehiclemaintenance.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.remarks1
     *
     * @param remarks1 the value for lg_vehiclemaintenance.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclemaintenance.remarks2
     *
     * @return the value of lg_vehiclemaintenance.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclemaintenance.remarks2
     *
     * @param remarks2 the value for lg_vehiclemaintenance.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehiclemaintenance
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vehiclemaintenanceid=").append(vehiclemaintenanceid);
        sb.append(", vehicleoperationid=").append(vehicleoperationid);
        sb.append(", mileage=").append(mileage);
        sb.append(", entertime=").append(entertime);
        sb.append(", factorytime=").append(factorytime);
        sb.append(", repairshop=").append(repairshop);
        sb.append(", maintenancelocation=").append(maintenancelocation);
        sb.append(", songcarren=").append(songcarren);
        sb.append(", hourcost=").append(hourcost);
        sb.append(", materialcost=").append(materialcost);
        sb.append(", aggregatecost=").append(aggregatecost);
        sb.append(", majorreplacementparts=").append(majorreplacementparts);
        sb.append(", damage=").append(damage);
        sb.append(", faultdescription=").append(faultdescription);
        sb.append(", repairdetails=").append(repairdetails);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}