package cn.log.pojo;

import java.io.Serializable;
import java.util.Date;

public class LgVehicledriverrecords implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicledriverrecords.vehicleDriverRecordsId
     *
     * @mbggenerated
     */
    private Integer vehicledriverrecordsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicledriverrecords.startingTime
     *
     * @mbggenerated
     */
    private Date startingtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicledriverrecords.deadLine
     *
     * @mbggenerated
     */
    private Date deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicledriverrecords.driverId
     *
     * @mbggenerated
     */
    private Integer driverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicledriverrecords.describe
     *
     * @mbggenerated
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicledriverrecords.managementType
     *
     * @mbggenerated
     */
    private Integer managementtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicledriverrecords.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicledriverrecords.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_vehicledriverrecords
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicledriverrecords.vehicleDriverRecordsId
     *
     * @return the value of lg_vehicledriverrecords.vehicleDriverRecordsId
     *
     * @mbggenerated
     */
    public Integer getVehicledriverrecordsid() {
        return vehicledriverrecordsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicledriverrecords.vehicleDriverRecordsId
     *
     * @param vehicledriverrecordsid the value for lg_vehicledriverrecords.vehicleDriverRecordsId
     *
     * @mbggenerated
     */
    public void setVehicledriverrecordsid(Integer vehicledriverrecordsid) {
        this.vehicledriverrecordsid = vehicledriverrecordsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicledriverrecords.startingTime
     *
     * @return the value of lg_vehicledriverrecords.startingTime
     *
     * @mbggenerated
     */
    public Date getStartingtime() {
        return startingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicledriverrecords.startingTime
     *
     * @param startingtime the value for lg_vehicledriverrecords.startingTime
     *
     * @mbggenerated
     */
    public void setStartingtime(Date startingtime) {
        this.startingtime = startingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicledriverrecords.deadLine
     *
     * @return the value of lg_vehicledriverrecords.deadLine
     *
     * @mbggenerated
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicledriverrecords.deadLine
     *
     * @param deadline the value for lg_vehicledriverrecords.deadLine
     *
     * @mbggenerated
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicledriverrecords.driverId
     *
     * @return the value of lg_vehicledriverrecords.driverId
     *
     * @mbggenerated
     */
    public Integer getDriverid() {
        return driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicledriverrecords.driverId
     *
     * @param driverid the value for lg_vehicledriverrecords.driverId
     *
     * @mbggenerated
     */
    public void setDriverid(Integer driverid) {
        this.driverid = driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicledriverrecords.describe
     *
     * @return the value of lg_vehicledriverrecords.describe
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicledriverrecords.describe
     *
     * @param describe the value for lg_vehicledriverrecords.describe
     *
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicledriverrecords.managementType
     *
     * @return the value of lg_vehicledriverrecords.managementType
     *
     * @mbggenerated
     */
    public Integer getManagementtype() {
        return managementtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicledriverrecords.managementType
     *
     * @param managementtype the value for lg_vehicledriverrecords.managementType
     *
     * @mbggenerated
     */
    public void setManagementtype(Integer managementtype) {
        this.managementtype = managementtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicledriverrecords.remarks1
     *
     * @return the value of lg_vehicledriverrecords.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicledriverrecords.remarks1
     *
     * @param remarks1 the value for lg_vehicledriverrecords.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicledriverrecords.remarks2
     *
     * @return the value of lg_vehicledriverrecords.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicledriverrecords.remarks2
     *
     * @param remarks2 the value for lg_vehicledriverrecords.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicledriverrecords
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vehicledriverrecordsid=").append(vehicledriverrecordsid);
        sb.append(", startingtime=").append(startingtime);
        sb.append(", deadline=").append(deadline);
        sb.append(", driverid=").append(driverid);
        sb.append(", describe=").append(describe);
        sb.append(", managementtype=").append(managementtype);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}