package cn.log.pojo;

import java.io.Serializable;

public class LgVehiclelineway implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclelineway.vehicleLineWayId
     *
     * @mbggenerated
     */
    private Integer vehiclelinewayid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclelineway.vehicleLineId
     *
     * @mbggenerated
     */
    private Integer vehiclelineid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclelineway.transferStationId
     *
     * @mbggenerated
     */
    private Integer transferstationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclelineway.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehiclelineway.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_vehiclelineway
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclelineway.vehicleLineWayId
     *
     * @return the value of lg_vehiclelineway.vehicleLineWayId
     *
     * @mbggenerated
     */
    public Integer getVehiclelinewayid() {
        return vehiclelinewayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclelineway.vehicleLineWayId
     *
     * @param vehiclelinewayid the value for lg_vehiclelineway.vehicleLineWayId
     *
     * @mbggenerated
     */
    public void setVehiclelinewayid(Integer vehiclelinewayid) {
        this.vehiclelinewayid = vehiclelinewayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclelineway.vehicleLineId
     *
     * @return the value of lg_vehiclelineway.vehicleLineId
     *
     * @mbggenerated
     */
    public Integer getVehiclelineid() {
        return vehiclelineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclelineway.vehicleLineId
     *
     * @param vehiclelineid the value for lg_vehiclelineway.vehicleLineId
     *
     * @mbggenerated
     */
    public void setVehiclelineid(Integer vehiclelineid) {
        this.vehiclelineid = vehiclelineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclelineway.transferStationId
     *
     * @return the value of lg_vehiclelineway.transferStationId
     *
     * @mbggenerated
     */
    public Integer getTransferstationid() {
        return transferstationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclelineway.transferStationId
     *
     * @param transferstationid the value for lg_vehiclelineway.transferStationId
     *
     * @mbggenerated
     */
    public void setTransferstationid(Integer transferstationid) {
        this.transferstationid = transferstationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclelineway.remarks1
     *
     * @return the value of lg_vehiclelineway.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclelineway.remarks1
     *
     * @param remarks1 the value for lg_vehiclelineway.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehiclelineway.remarks2
     *
     * @return the value of lg_vehiclelineway.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehiclelineway.remarks2
     *
     * @param remarks2 the value for lg_vehiclelineway.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehiclelineway
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vehiclelinewayid=").append(vehiclelinewayid);
        sb.append(", vehiclelineid=").append(vehiclelineid);
        sb.append(", transferstationid=").append(transferstationid);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}