package cn.log.pojo;

import java.io.Serializable;

public class LgVehicleline implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicleline.vehicleLineId
     *
     * @mbggenerated
     */
    private Integer vehiclelineid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicleline.lineName
     *
     * @mbggenerated
     */
    private String linename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicleline.vehicleRoute
     *
     * @mbggenerated
     */
    private String vehicleroute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicleline.lineStatus
     *
     * @mbggenerated
     */
    private Integer linestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicleline.departurePoint
     *
     * @mbggenerated
     */
    private String departurepoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicleline.destinationNode
     *
     * @mbggenerated
     */
    private String destinationnode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicleline.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_vehicleline.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_vehicleline
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicleline.vehicleLineId
     *
     * @return the value of lg_vehicleline.vehicleLineId
     *
     * @mbggenerated
     */
    public Integer getVehiclelineid() {
        return vehiclelineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicleline.vehicleLineId
     *
     * @param vehiclelineid the value for lg_vehicleline.vehicleLineId
     *
     * @mbggenerated
     */
    public void setVehiclelineid(Integer vehiclelineid) {
        this.vehiclelineid = vehiclelineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicleline.lineName
     *
     * @return the value of lg_vehicleline.lineName
     *
     * @mbggenerated
     */
    public String getLinename() {
        return linename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicleline.lineName
     *
     * @param linename the value for lg_vehicleline.lineName
     *
     * @mbggenerated
     */
    public void setLinename(String linename) {
        this.linename = linename == null ? null : linename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicleline.vehicleRoute
     *
     * @return the value of lg_vehicleline.vehicleRoute
     *
     * @mbggenerated
     */
    public String getVehicleroute() {
        return vehicleroute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicleline.vehicleRoute
     *
     * @param vehicleroute the value for lg_vehicleline.vehicleRoute
     *
     * @mbggenerated
     */
    public void setVehicleroute(String vehicleroute) {
        this.vehicleroute = vehicleroute == null ? null : vehicleroute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicleline.lineStatus
     *
     * @return the value of lg_vehicleline.lineStatus
     *
     * @mbggenerated
     */
    public Integer getLinestatus() {
        return linestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicleline.lineStatus
     *
     * @param linestatus the value for lg_vehicleline.lineStatus
     *
     * @mbggenerated
     */
    public void setLinestatus(Integer linestatus) {
        this.linestatus = linestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicleline.departurePoint
     *
     * @return the value of lg_vehicleline.departurePoint
     *
     * @mbggenerated
     */
    public String getDeparturepoint() {
        return departurepoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicleline.departurePoint
     *
     * @param departurepoint the value for lg_vehicleline.departurePoint
     *
     * @mbggenerated
     */
    public void setDeparturepoint(String departurepoint) {
        this.departurepoint = departurepoint == null ? null : departurepoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicleline.destinationNode
     *
     * @return the value of lg_vehicleline.destinationNode
     *
     * @mbggenerated
     */
    public String getDestinationnode() {
        return destinationnode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicleline.destinationNode
     *
     * @param destinationnode the value for lg_vehicleline.destinationNode
     *
     * @mbggenerated
     */
    public void setDestinationnode(String destinationnode) {
        this.destinationnode = destinationnode == null ? null : destinationnode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicleline.remarks1
     *
     * @return the value of lg_vehicleline.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicleline.remarks1
     *
     * @param remarks1 the value for lg_vehicleline.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_vehicleline.remarks2
     *
     * @return the value of lg_vehicleline.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_vehicleline.remarks2
     *
     * @param remarks2 the value for lg_vehicleline.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_vehicleline
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vehiclelineid=").append(vehiclelineid);
        sb.append(", linename=").append(linename);
        sb.append(", vehicleroute=").append(vehicleroute);
        sb.append(", linestatus=").append(linestatus);
        sb.append(", departurepoint=").append(departurepoint);
        sb.append(", destinationnode=").append(destinationnode);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}