package cn.log.pojo;

import java.io.Serializable;
import java.util.Date;

public class LgWarehousing implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehousing.warehousingId
     *
     * @mbggenerated
     */
    private Integer warehousingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehousing.warehousesNumber
     *
     * @mbggenerated
     */
    private Integer warehousesnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehousing.warehousingTime
     *
     * @mbggenerated
     */
    private Date warehousingtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehousing.cargoDamaged
     *
     * @mbggenerated
     */
    private Integer cargodamaged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehousing.goodsDamageId
     *
     * @mbggenerated
     */
    private Integer goodsdamageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehousing.storekeeperId
     *
     * @mbggenerated
     */
    private Integer storekeeperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehousing.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehousing.warehouseId
     *
     * @mbggenerated
     */
    private Integer warehouseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehousing.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehousing.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_warehousing
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehousing.warehousingId
     *
     * @return the value of lg_warehousing.warehousingId
     *
     * @mbggenerated
     */
    public Integer getWarehousingid() {
        return warehousingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehousing.warehousingId
     *
     * @param warehousingid the value for lg_warehousing.warehousingId
     *
     * @mbggenerated
     */
    public void setWarehousingid(Integer warehousingid) {
        this.warehousingid = warehousingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehousing.warehousesNumber
     *
     * @return the value of lg_warehousing.warehousesNumber
     *
     * @mbggenerated
     */
    public Integer getWarehousesnumber() {
        return warehousesnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehousing.warehousesNumber
     *
     * @param warehousesnumber the value for lg_warehousing.warehousesNumber
     *
     * @mbggenerated
     */
    public void setWarehousesnumber(Integer warehousesnumber) {
        this.warehousesnumber = warehousesnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehousing.warehousingTime
     *
     * @return the value of lg_warehousing.warehousingTime
     *
     * @mbggenerated
     */
    public Date getWarehousingtime() {
        return warehousingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehousing.warehousingTime
     *
     * @param warehousingtime the value for lg_warehousing.warehousingTime
     *
     * @mbggenerated
     */
    public void setWarehousingtime(Date warehousingtime) {
        this.warehousingtime = warehousingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehousing.cargoDamaged
     *
     * @return the value of lg_warehousing.cargoDamaged
     *
     * @mbggenerated
     */
    public Integer getCargodamaged() {
        return cargodamaged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehousing.cargoDamaged
     *
     * @param cargodamaged the value for lg_warehousing.cargoDamaged
     *
     * @mbggenerated
     */
    public void setCargodamaged(Integer cargodamaged) {
        this.cargodamaged = cargodamaged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehousing.goodsDamageId
     *
     * @return the value of lg_warehousing.goodsDamageId
     *
     * @mbggenerated
     */
    public Integer getGoodsdamageid() {
        return goodsdamageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehousing.goodsDamageId
     *
     * @param goodsdamageid the value for lg_warehousing.goodsDamageId
     *
     * @mbggenerated
     */
    public void setGoodsdamageid(Integer goodsdamageid) {
        this.goodsdamageid = goodsdamageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehousing.storekeeperId
     *
     * @return the value of lg_warehousing.storekeeperId
     *
     * @mbggenerated
     */
    public Integer getStorekeeperid() {
        return storekeeperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehousing.storekeeperId
     *
     * @param storekeeperid the value for lg_warehousing.storekeeperId
     *
     * @mbggenerated
     */
    public void setStorekeeperid(Integer storekeeperid) {
        this.storekeeperid = storekeeperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehousing.remarks
     *
     * @return the value of lg_warehousing.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehousing.remarks
     *
     * @param remarks the value for lg_warehousing.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehousing.warehouseId
     *
     * @return the value of lg_warehousing.warehouseId
     *
     * @mbggenerated
     */
    public Integer getWarehouseid() {
        return warehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehousing.warehouseId
     *
     * @param warehouseid the value for lg_warehousing.warehouseId
     *
     * @mbggenerated
     */
    public void setWarehouseid(Integer warehouseid) {
        this.warehouseid = warehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehousing.remarks1
     *
     * @return the value of lg_warehousing.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehousing.remarks1
     *
     * @param remarks1 the value for lg_warehousing.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehousing.remarks2
     *
     * @return the value of lg_warehousing.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehousing.remarks2
     *
     * @param remarks2 the value for lg_warehousing.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_warehousing
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", warehousingid=").append(warehousingid);
        sb.append(", warehousesnumber=").append(warehousesnumber);
        sb.append(", warehousingtime=").append(warehousingtime);
        sb.append(", cargodamaged=").append(cargodamaged);
        sb.append(", goodsdamageid=").append(goodsdamageid);
        sb.append(", storekeeperid=").append(storekeeperid);
        sb.append(", remarks=").append(remarks);
        sb.append(", warehouseid=").append(warehouseid);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}