package cn.log.pojo;

import java.io.Serializable;

public class LgWaybillgoods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_waybillgoods.wayBillGoodsId
     *
     * @mbggenerated
     */
    private Integer waybillgoodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_waybillgoods.wayBillId
     *
     * @mbggenerated
     */
    private Integer waybillid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_waybillgoods.goodsId
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_waybillgoods
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_waybillgoods.wayBillGoodsId
     *
     * @return the value of lg_waybillgoods.wayBillGoodsId
     *
     * @mbggenerated
     */
    public Integer getWaybillgoodsid() {
        return waybillgoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_waybillgoods.wayBillGoodsId
     *
     * @param waybillgoodsid the value for lg_waybillgoods.wayBillGoodsId
     *
     * @mbggenerated
     */
    public void setWaybillgoodsid(Integer waybillgoodsid) {
        this.waybillgoodsid = waybillgoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_waybillgoods.wayBillId
     *
     * @return the value of lg_waybillgoods.wayBillId
     *
     * @mbggenerated
     */
    public Integer getWaybillid() {
        return waybillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_waybillgoods.wayBillId
     *
     * @param waybillid the value for lg_waybillgoods.wayBillId
     *
     * @mbggenerated
     */
    public void setWaybillid(Integer waybillid) {
        this.waybillid = waybillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_waybillgoods.goodsId
     *
     * @return the value of lg_waybillgoods.goodsId
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_waybillgoods.goodsId
     *
     * @param goodsid the value for lg_waybillgoods.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_waybillgoods
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", waybillgoodsid=").append(waybillgoodsid);
        sb.append(", waybillid=").append(waybillid);
        sb.append(", goodsid=").append(goodsid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}