package cn.log.pojo;

import java.io.Serializable;

public class LgWarehousinggoods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehousinggoods.warehousingGoodsId
     *
     * @mbggenerated
     */
    private Integer warehousinggoodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehousinggoods.warehousingId
     *
     * @mbggenerated
     */
    private Integer warehousingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehousinggoods.goodsId
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehousinggoods.warehousingQuantity
     *
     * @mbggenerated
     */
    private Integer warehousingquantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_warehousinggoods
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehousinggoods.warehousingGoodsId
     *
     * @return the value of lg_warehousinggoods.warehousingGoodsId
     *
     * @mbggenerated
     */
    public Integer getWarehousinggoodsid() {
        return warehousinggoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehousinggoods.warehousingGoodsId
     *
     * @param warehousinggoodsid the value for lg_warehousinggoods.warehousingGoodsId
     *
     * @mbggenerated
     */
    public void setWarehousinggoodsid(Integer warehousinggoodsid) {
        this.warehousinggoodsid = warehousinggoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehousinggoods.warehousingId
     *
     * @return the value of lg_warehousinggoods.warehousingId
     *
     * @mbggenerated
     */
    public Integer getWarehousingid() {
        return warehousingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehousinggoods.warehousingId
     *
     * @param warehousingid the value for lg_warehousinggoods.warehousingId
     *
     * @mbggenerated
     */
    public void setWarehousingid(Integer warehousingid) {
        this.warehousingid = warehousingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehousinggoods.goodsId
     *
     * @return the value of lg_warehousinggoods.goodsId
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehousinggoods.goodsId
     *
     * @param goodsid the value for lg_warehousinggoods.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehousinggoods.warehousingQuantity
     *
     * @return the value of lg_warehousinggoods.warehousingQuantity
     *
     * @mbggenerated
     */
    public Integer getWarehousingquantity() {
        return warehousingquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehousinggoods.warehousingQuantity
     *
     * @param warehousingquantity the value for lg_warehousinggoods.warehousingQuantity
     *
     * @mbggenerated
     */
    public void setWarehousingquantity(Integer warehousingquantity) {
        this.warehousingquantity = warehousingquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_warehousinggoods
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", warehousinggoodsid=").append(warehousinggoodsid);
        sb.append(", warehousingid=").append(warehousingid);
        sb.append(", goodsid=").append(goodsid);
        sb.append(", warehousingquantity=").append(warehousingquantity);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}