package cn.log.pojo;

import java.io.Serializable;
import java.util.Date;

public class LgWarehouse implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehouse.warehouseId
     *
     * @mbggenerated
     */
    private Integer warehouseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehouse.transferStationId
     *
     * @mbggenerated
     */
    private Integer transferstationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehouse.warehouseNumber
     *
     * @mbggenerated
     */
    private String warehousenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehouse.warehouseName
     *
     * @mbggenerated
     */
    private String warehousename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehouse.warehouseArea
     *
     * @mbggenerated
     */
    private Double warehousearea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehouse.heapHeight
     *
     * @mbggenerated
     */
    private Double heapheight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehouse.openingDate
     *
     * @mbggenerated
     */
    private Date openingdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehouse.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lg_warehouse.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lg_warehouse
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehouse.warehouseId
     *
     * @return the value of lg_warehouse.warehouseId
     *
     * @mbggenerated
     */
    public Integer getWarehouseid() {
        return warehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehouse.warehouseId
     *
     * @param warehouseid the value for lg_warehouse.warehouseId
     *
     * @mbggenerated
     */
    public void setWarehouseid(Integer warehouseid) {
        this.warehouseid = warehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehouse.transferStationId
     *
     * @return the value of lg_warehouse.transferStationId
     *
     * @mbggenerated
     */
    public Integer getTransferstationid() {
        return transferstationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehouse.transferStationId
     *
     * @param transferstationid the value for lg_warehouse.transferStationId
     *
     * @mbggenerated
     */
    public void setTransferstationid(Integer transferstationid) {
        this.transferstationid = transferstationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehouse.warehouseNumber
     *
     * @return the value of lg_warehouse.warehouseNumber
     *
     * @mbggenerated
     */
    public String getWarehousenumber() {
        return warehousenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehouse.warehouseNumber
     *
     * @param warehousenumber the value for lg_warehouse.warehouseNumber
     *
     * @mbggenerated
     */
    public void setWarehousenumber(String warehousenumber) {
        this.warehousenumber = warehousenumber == null ? null : warehousenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehouse.warehouseName
     *
     * @return the value of lg_warehouse.warehouseName
     *
     * @mbggenerated
     */
    public String getWarehousename() {
        return warehousename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehouse.warehouseName
     *
     * @param warehousename the value for lg_warehouse.warehouseName
     *
     * @mbggenerated
     */
    public void setWarehousename(String warehousename) {
        this.warehousename = warehousename == null ? null : warehousename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehouse.warehouseArea
     *
     * @return the value of lg_warehouse.warehouseArea
     *
     * @mbggenerated
     */
    public Double getWarehousearea() {
        return warehousearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehouse.warehouseArea
     *
     * @param warehousearea the value for lg_warehouse.warehouseArea
     *
     * @mbggenerated
     */
    public void setWarehousearea(Double warehousearea) {
        this.warehousearea = warehousearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehouse.heapHeight
     *
     * @return the value of lg_warehouse.heapHeight
     *
     * @mbggenerated
     */
    public Double getHeapheight() {
        return heapheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehouse.heapHeight
     *
     * @param heapheight the value for lg_warehouse.heapHeight
     *
     * @mbggenerated
     */
    public void setHeapheight(Double heapheight) {
        this.heapheight = heapheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehouse.openingDate
     *
     * @return the value of lg_warehouse.openingDate
     *
     * @mbggenerated
     */
    public Date getOpeningdate() {
        return openingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehouse.openingDate
     *
     * @param openingdate the value for lg_warehouse.openingDate
     *
     * @mbggenerated
     */
    public void setOpeningdate(Date openingdate) {
        this.openingdate = openingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehouse.remarks1
     *
     * @return the value of lg_warehouse.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehouse.remarks1
     *
     * @param remarks1 the value for lg_warehouse.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lg_warehouse.remarks2
     *
     * @return the value of lg_warehouse.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lg_warehouse.remarks2
     *
     * @param remarks2 the value for lg_warehouse.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lg_warehouse
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", warehouseid=").append(warehouseid);
        sb.append(", transferstationid=").append(transferstationid);
        sb.append(", warehousenumber=").append(warehousenumber);
        sb.append(", warehousename=").append(warehousename);
        sb.append(", warehousearea=").append(warehousearea);
        sb.append(", heapheight=").append(heapheight);
        sb.append(", openingdate=").append(openingdate);
        sb.append(", remarks1=").append(remarks1);
        sb.append(", remarks2=").append(remarks2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}